{
 "title": "Apache IoTDB Performance Overview Dashboard",
 "description": "Performance Overview Dashboard of Apache IoTDB",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_cpu_cores{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_disk_total_space{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Timeseries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantity{instance=\"$instance\", name=\"timeSeries\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_load{instance=~\"$instance\"} / 100",
     "legendFormat": "cpu load"
    },
    {
     "expr": "1- sys_disk_free_space{instance=~\"$instance\"} / sys_disk_total_space{instance=~\"$instance\"}",
     "legendFormat": "disk"
    },
    {
     "expr": "1 - process_free_mem{instance=\"$instance\"} / process_total_mem{instance=\"$instance\"}",
     "legendFormat": "process memory"
    },
    {
     "expr": "1 - sys_free_physical_memory_size{instance=\"$instance\", name=\"system\"} / sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "system memory"
    }
   ]
  },
  {
   "title": "Write Point Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "rate(quantity_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total File Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(file_count{instance=\"$instance\", name!=\"open_file_handlers\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(performance_overview_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "operation {{type}} {{interface}}"
    },
    {
     "expr": "rate(entry_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "rpc {{name}}"
    }
   ]
  },
  {
   "title": "OPS Of Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(performance_overview_detail_seconds_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "OPS Of Schedule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(performance_overview_schedule_detail_seconds_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Time Consumed Of Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "performance_overview_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "{{type}} - {{interface}} - 99"
    },
    {
     "expr": "sum(rate(performance_overview_seconds_sum{instance=~\"$instance\"}[1m]) / rate(performance_overview_seconds_count{instance=~\"$instance\"}[1m])) by (instance, interface, type)",
     "legendFormat": "{{type}} - {{interface}} - avg"
    }
   ]
  },
  {
   "title": "Average Time Consumed Of Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(entry_seconds_sum{instance=\"$instance\"}[1m]) / rate(entry_seconds_count{instance=\"$instance\"}[1m])) by (instance, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "P99 Time Consumed Of Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "entry_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Session Idle Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(session_idle_time_sum{instance=\"$instance\"}[1m])) / sum(rate(session_idle_time_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Average Idle"
    },
    {
     "expr": "sum(rate(performance_overview_seconds_sum{instance=~\"$instance\"}[1m])) / sum(rate(performance_overview_seconds_count{instance=~\"$instance\"}[1m])) * 1000000000",
     "legendFormat": "Average Busy"
    }
   ]
  },
  {
   "title": "Client Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "thrift_connections{instance=~\"$instance\", name=~\".*Client.*\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "thrift_active_threads{instance=~\"$instance\", name=~\".*Client.*\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Average Time Consumed Of Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(performance_overview_detail_seconds_sum{instance=\"$instance\"}[1m]) / rate(performance_overview_detail_seconds_count{instance=\"$instance\"}[1m])) by (instance, stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "P99 Time Consumed Of Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "performance_overview_detail_seconds{instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Average Time Consumed Of Schedule Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(performance_overview_schedule_overview_seconds_sum{instance=\"$instance\"}[1m]) / rate(performance_overview_schedule_overview_seconds_count{instance=\"$instance\"}[1m])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "P99 Time Consumed Of Schedule Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "performance_overview_schedule_overview_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Average Time Consumed Of Schedule Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(performance_overview_schedule_detail_seconds_sum{instance=\"$instance\"}[1m]) / rate(performance_overview_schedule_detail_seconds_count{instance=\"$instance\"}[1m])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "P99 Time Consumed Of Schedule Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "performance_overview_schedule_detail_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Task Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "queue{instance=~\"$instance\"}",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Average Time Consumed of Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cost_task_seconds_sum{instance=~\"$instance\"}[1m])/rate(cost_task_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "P99 Time Consumed of Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cost_task_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu_load{instance=\"$instance\",name=\"system\"}",
     "legendFormat": "System CPU Load"
    },
    {
     "expr": "process_cpu_load{instance=\"$instance\",name=\"process\"}",
     "legendFormat": "Process CPU Load"
    }
   ]
  },
  {
   "title": "CPU Time Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time{instance=\"$instance\", name=\"process\"}[1m]))*60",
     "legendFormat": "System CPU Load"
    }
   ]
  },
  {
   "title": "GC Time Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
     "legendFormat": "Young GC"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
     "legendFormat": "Full GC"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Maximum heap memory"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Used heap memory"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Off Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_buffer_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "off heap memory"
    }
   ]
  },
  {
   "title": "The Number Of Java Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "File Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "file_count{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(file_count{instance=~\"$instance\", name!=\"open_file_handlers\"})",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "File Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "file_size{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(file_size{instance=~\"$instance\"})",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Log Number Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{instance=~\"${instance}\"}[1m])) by (level) * 60",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}