{
 "title": "Apache IoTDB Disk I/O Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   },
   { "name": "disk", "query": { "query": "label_values(disk_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Disk Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O Busy Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "disk_io_busy_percentage{instance=~\"$instance\", disk_id=~\"$disk\"}",
       "legendFormat": "{{disk_id}}"
      }
     ]
    },
    {
     "title": "Disk I/O Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rate(disk_io_size{instance=~\"$instance\", disk_id=~\"$disk\"}[1m])",
       "legendFormat": "{{disk_id}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(disk_io_ops{instance=~\"$instance\", disk_id=~\"$disk\"}[1m])",
       "legendFormat": "{{disk_id}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk Per I/O Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_io_avg_time{instance=~\"$instance\", disk_id=~\"$disk\"}",
       "legendFormat": "{{disk_id}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Avg Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_io_avg_size{instance=~\"$instance\", disk_id=~\"$disk\"}",
       "legendFormat": "{{disk_id}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Avg Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "disk_io_avg_queue_size{instance=~\"$instance\", disk_id=~\"$disk\"}",
       "legendFormat": "{{disk_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process I/O Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rate(process_io_size{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{from}}-{{name}}"
      }
     ]
    },
    {
     "title": "I/O System Call Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(process_io_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{from}}-{{name}}"
      }
     ]
    }
   ]
  }
 ]
}