{
 "title": "Apache IoTDB Network Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "iface", "query": { "query": "label_values(iface_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Net Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(received_bytes{instance=~\"$instance\", iface_name=~\"$iface\"}[1m])",
     "legendFormat": "{{iface_name}}-{{type}}"
    },
    {
     "expr": "rate(transmitted_bytes{instance=~\"$instance\", iface_name=~\"$iface\"}[1m])",
     "legendFormat": "{{iface_name}}-{{type}}"
    }
   ]
  },
  {
   "title": "Receive/Transmit Data Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "received_bytes{instance=~\"$instance\",iface_name=~\"$iface\"}",
     "legendFormat": "{{iface_name}}-{{type}}"
    },
    {
     "expr": "transmitted_bytes{instance=~\"$instance\",iface_name=~\"$iface\"}",
     "legendFormat": "{{iface_name}}-{{type}}"
    }
   ]
  },
  {
   "title": "Packet Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(received_packets{instance=~\"$instance\", iface_name=~\"$iface\"}[1m])",
     "legendFormat": "{{iface_name}}-{{type}}"
    },
    {
     "expr": "rate(transmitted_packets{instance=~\"$instance\", iface_name=~\"$iface\"}[1m])",
     "legendFormat": "{{iface_name}}-{{type}}"
    }
   ]
  },
  {
   "title": "Connection Num",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "connection_num{instance=~\"$instance\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  }
 ]
}