{
 "title": "Apache IoTDB DataNode Dashboard",
 "tags": [
  "Apache-IoTDB",
  "DataNode",
  "v1.0"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "The Number Of Entity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "quantity{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Write Point Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "rate(quantity_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "write point per second"
      }
     ]
    },
    {
     "title": "Database Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mem{instance=~\"$instance\", name!=\"IoTConsensus\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "The Time Consumed Of Operation (50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "statement_execution_seconds{instance=~\"$instance\", quantile=\"0.5\"}",
       "legendFormat": "{{type}}/{{interface}}"
      }
     ]
    },
    {
     "title": "The Time Consumed Of Operation (75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "statement_execution_seconds{instance=~\"$instance\", quantile=\"0.75\"}",
       "legendFormat": "{{type}}/{{interface}}"
      }
     ]
    },
    {
     "title": "The Time Consumed Of Operation (100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "statement_execution_seconds{instance=~\"$instance\", quantile=\"1.0\"}",
       "legendFormat": "{{type}}/{{interface}}"
      }
     ]
    },
    {
     "title": "The QPS Of Interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(entry_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The Time Consumed Of Interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(entry_seconds_sum{instance=~\"$instance\"}[1m])/rate(entry_seconds_count{instance=~\"$instance\"}[1m])) by (name,instance)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(cache_total{instance=~\"$instance\", type=\"hit\"}) by (name) / avg(cache_total{instance=~\"$instance\", type=\"all\"}) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "cache_hit{instance=~\"$instance\"} / 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thrift Connection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "thrift_connections{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thrift Active Thread",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "thrift_active_threads{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "queue{instance=~\"$instance\"}",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "The Time Consumed of Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cost_task_seconds_sum{instance=~\"$instance\"}[1m])/rate(cost_task_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Compaction Read And Write Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(data_written_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(data_read_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Compaction R/W Ratio Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(data_read_total{instance=~\"$instance\"}[1m]))*60 / sum(rate(data_written_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Compaction Number Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(compaction_task_count_total{instance=\"$instance\", name = \"inner_compaction\", type=\"sequence\"}[1m]))*60",
     "legendFormat": "sequence"
    },
    {
     "expr": "sum(rate(compaction_task_count_total{instance=\"$instance\", name = \"inner_compaction\", type=\"unsequence\"}[1m]))*60",
     "legendFormat": "unsequence"
    },
    {
     "expr": "sum(rate(compaction_task_count_total{instance=\"$instance\", name = \"cross_compaction\", type=\"cross\"}[1m]))*60",
     "legendFormat": "cross"
    }
   ]
  },
  {
   "title": "Compaction Process Chunk Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(Compacted_Chunk_Num_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Compacted Chunk Num Per Min"
    },
    {
     "expr": "sum(rate(Deserialized_Chunk_Num_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Deserialized Chunk Num Per Min"
    },
    {
     "expr": "sum(rate(Directly_Flush_Chunk_Num_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Directly Flush Chunk Num Per Min"
    },
    {
     "expr": "sum(rate(Merged_Chunk_Num_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Merged Chunk Num Per Min"
    }
   ]
  },
  {
   "title": "Compacted Point Num Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(Compacted_Point_Num_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Compacted Point Num Per Min"
    }
   ]
  },
  {
   "title": "Query Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "The time consumed of query plan stages(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(query_plan_cost_seconds_sum{instance=~\"$instance\"}[1m]) / rate(query_plan_cost_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query plan stages(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "query_plan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query plan stages(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "query_plan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query plan stages(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "query_plan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of plan dispatch stages(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(dispatcher_seconds_sum{instance=~\"$instance\"}[1m]) / rate(dispatcher_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of plan dispatch stages(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dispatcher_seconds{instance=~\"${instance}\", quantile=\"0.5\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of plan dispatch stages(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dispatcher_seconds{instance=~\"${instance}\", quantile=\"0.75\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of plan dispatch stages(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dispatcher_seconds{instance=~\"${instance}\", quantile=\"1.0\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query execution stages(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(query_execution_seconds_sum{instance=~\"$instance\"}[1m]) / rate(query_execution_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query execution stages(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "query_execution_seconds{instance=~\"${instance}\", quantile=\"0.5\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query execution stages(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "query_execution_seconds{instance=~\"${instance}\", quantile=\"0.75\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query execution stages(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "query_execution_seconds{instance=~\"${instance}\", quantile=\"1.0\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of operator execution stages(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(operator_execution_cost_seconds_sum{instance=~\"$instance\"}[1m]) / rate(operator_execution_cost_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The time consumed of operator execution(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "operator_execution_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The time consumed of operator execution(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "operator_execution_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The time consumed of operator execution(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "operator_execution_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The time consumed of query aggregation(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aggregation_seconds_sum{instance=~\"$instance\"}[1m]) / rate(aggregation_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of query aggregation(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "aggregation_seconds{instance=~\"${instance}\", quantile=\"0.5\"}",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of query aggregation(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "aggregation_seconds{instance=~\"${instance}\", quantile=\"0.75\"}",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of query aggregation(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "aggregation_seconds{instance=~\"${instance}\", quantile=\"1.0\"}",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of query scan(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(series_scan_cost_seconds_sum{instance=~\"$instance\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query scan(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(series_scan_cost_seconds{instance=~\"$instance\", quantile=\"0.5\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query scan(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(series_scan_cost_seconds{instance=~\"$instance\", quantile=\"0.75\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The time consumed of query scan(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(series_scan_cost_seconds{instance=~\"$instance\", quantile=\"1.0\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "The usage of query resource(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(query_resource_sum{instance=~\"$instance\"}[1m]) / rate(query_resource_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The usage of query resource(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "query_resource{instance=~\"${instance}\", quantile=\"0.5\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The usage of query resource(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "query_resource{instance=~\"${instance}\", quantile=\"0.75\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The usage of query resource(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "query_resource{instance=~\"${instance}\", quantile=\"1.0\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of query data exchange(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(data_exchange_cost_seconds_sum{instance=~\"$instance\"}[1m]) / rate(data_exchange_cost_seconds_count{instance=~\"$instance\"}[1m])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "The time consumed  of query data exchange(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(data_exchange_cost_seconds{instance=~\"$instance\", quantile=\"0.5\"}[1m])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "The time consumed  of query data exchange(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(data_exchange_cost_seconds{instance=~\"$instance\", quantile=\"0.75\"}[1m])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "The time consumed  of query data exchange(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(data_exchange_cost_seconds{instance=~\"$instance\", quantile=\"1.0\"}[1m])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "The count of Data Exchange(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(data_exchange_count_sum{instance=~\"$instance\"}[1m]) / rate(data_exchange_count_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The count of Data Exchange",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "data_exchange_count{instance=~\"$instance\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "The number of query queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "driver_scheduler{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The time consumed of query schedule time(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(driver_scheduler_seconds_sum{instance=~\"$instance\"}[1m]) / rate(driver_scheduler_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The time consumed of query schedule time(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "driver_scheduler_seconds{instance=~\"$instance\", quantile=\"0.5\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The time consumed of query schedule time(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "driver_scheduler_seconds{instance=~\"$instance\", quantile=\"0.75\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "The time consumed of query schedule time(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "driver_scheduler_seconds{instance=~\"$instance\", quantile=\"1.0\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "The time consumed of load timeseries metadata(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"load_timeseries_metadata\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"load_timeseries_metadata\"}[1m])",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of load timeseries metadata(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"load_timeseries_metadata\"}",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of load timeseries metadata(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"load_timeseries_metadata\"}",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of load timeseries metadata(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"load_timeseries_metadata\"}",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of read timeseries metadata(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"read_timeseries_metadata\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"read_timeseries_metadata\"}[1m])",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of read timeseries metadata(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"read_timeseries_metadata\"}",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of read timeseries metadata(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"read_timeseries_metadata\"}",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of read timeseries metadata(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"read_timeseries_metadata\"}",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of timeseries metadata modification(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"timeseries_metadata_modification\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"timeseries_metadata_modification\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of timeseries metadata modification(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"timeseries_metadata_modification\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of timeseries metadata modification(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"timeseries_metadata_modification\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of timeseries metadata modification(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"timeseries_metadata_modification\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of load chunk metadata list(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"load_chunk_metadata_list\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"load_chunk_metadata_list\"}[1m])",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of load chunk metadata list(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"load_chunk_metadata_list\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of load chunk metadata list(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"load_chunk_metadata_list\"}",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of load chunk metadata list(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"load_chunk_metadata_list\"}",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of chunk metadata modification(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"chunk_metadata_modification\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"chunk_metadata_modification\"}[1m])",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of chunk metadata modification(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"chunk_metadata_modification\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of chunk metadata modification(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"chunk_metadata_modification\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of chunk metadata modification(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"chunk_metadata_modification\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of chunk metadata filter(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"chunk_metadata_filter\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"chunk_metadata_filter\"}[1m])",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of chunk metadata filter(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"chunk_metadata_filter\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of chunk metadata filter(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"chunk_metadata_filter\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of chunk metadata filter(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"chunk_metadata_filter\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of construct chunk reader(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"construct_chunk_reader\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"construct_chunk_reader\"}[1m])",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of construct chunk reader(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"construct_chunk_reader\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of construct chunk reader(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"construct_chunk_reader\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of construct chunk reader(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"construct_chunk_reader\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of read chunk(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"read_chunk\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"read_chunk\"}[1m])",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of read chunk(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"read_chunk\"}",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of read chunk(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"read_chunk\"}",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of read chunk(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"read_chunk\"}",
       "legendFormat": "{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of init chunk reader(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"init_chunk_reader\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"init_chunk_reader\"}[1m])",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of init chunk reader(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"init_chunk_reader\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of init chunk reader(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"init_chunk_reader\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of init chunk reader(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"init_chunk_reader\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of build tsblock from page reader(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"build_tsblock_from_page_reader\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"build_tsblock_from_page_reader\"}[1m])",
       "legendFormat": "{{type}}_{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of build tsblock from page reader(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"build_tsblock_from_page_reader\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of build tsblock from page reader(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"build_tsblock_from_page_reader\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of build tsblock from page reader(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"build_tsblock_from_page_reader\"}",
       "legendFormat": "{{type}}-{{from}}"
      }
     ]
    },
    {
     "title": "The time consumed of build tsblock from merge reader(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(series_scan_cost_seconds_sum{instance=~\"$instance\", stage=\"build_tsblock_from_merge_reader\"}[1m]) / rate(series_scan_cost_seconds_count{instance=~\"$instance\", stage=\"build_tsblock_from_merge_reader\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of build tsblock from merge reader(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.5\", stage=\"build_tsblock_from_merge_reader\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of build tsblock from merge reader(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"0.75\", stage=\"build_tsblock_from_merge_reader\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of build tsblock from merge reader(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "series_scan_cost_seconds{instance=~\"${instance}\", quantile=\"1.0\", stage=\"build_tsblock_from_merge_reader\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Data Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "The time consumed of source handle get tsblock(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(data_exchange_cost_seconds_sum{instance=~\"$instance\", operation=\"source_handle_get_tsblock\"}[1m]) / rate(data_exchange_cost_seconds_count{instance=~\"$instance\", operation=\"source_handle_get_tsblock\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The  time consumed of source handle get tsblock(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"source_handle_get_tsblock\", quantile=\"0.5\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The  time consumed of source handle get tsblock(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"source_handle_get_tsblock\", quantile=\"0.75\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The  time consumed of source handle get tsblock(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"source_handle_get_tsblock\", quantile=\"1.0\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The  time consumed of source handle deserialize tsblock(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(data_exchange_cost_seconds_sum{instance=~\"$instance\", operation=\"source_handle_deserialize_tsblock\"}[1m]) / rate(data_exchange_cost_seconds_count{instance=~\"$instance\", operation=\"source_handle_deserialize_tsblock\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of source handle deserialize tsblock(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"source_handle_deserialize_tsblock\", quantile=\"0.5\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of source handle deserialize tsblock(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"source_handle_deserialize_tsblock\", quantile=\"0.75\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of source handle deserialize tsblock(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"source_handle_deserialize_tsblock\", quantile=\"1.0\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of sink handle send tsblock(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(data_exchange_cost_seconds_sum{instance=~\"$instance\", operation=\"sink_handle_send_tsblock\"}[1m]) / rate(data_exchange_cost_seconds_count{instance=~\"$instance\", operation=\"sink_handle_send_tsblock\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of sink handle send tsblock(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"sink_handle_send_tsblock\", quantile=\"0.5\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of sink handle send tsblock(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"sink_handle_send_tsblock\", quantile=\"0.75\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of sink handle send tsblock(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"sink_handle_send_tsblock\", quantile=\"1.0\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of on acknowledge data block event task(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(data_exchange_cost_seconds_sum{instance=~\"$instance\", operation=\"on_acknowledge_data_block_event_task\"}[1m]) / rate(data_exchange_cost_seconds_count{instance=~\"$instance\", operation=\"on_acknowledge_data_block_event_task\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed of on acknowledge data block event task(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"on_acknowledge_data_block_event_task\", quantile=\"0.5\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of on acknowledge data block event task(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"on_acknowledge_data_block_event_task\", quantile=\"0.75\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of on acknowledge data block event task(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"on_acknowledge_data_block_event_task\", quantile=\"1.0\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of get data block task(avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(data_exchange_cost_seconds_sum{instance=~\"$instance\", operation=\"get_data_block_task\"}[1m]) / rate(data_exchange_cost_seconds_count{instance=~\"$instance\", operation=\"get_data_block_task\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of get data block task(50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"get_data_block_task\", quantile=\"0.5\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of get data block task(75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"get_data_block_task\", quantile=\"0.75\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The time consumed  of get data block task(100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "data_exchange_cost_seconds{instance=~\"$instance\", operation=\"get_data_block_task\", quantile=\"1.0\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IoT Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IoTConsensus Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mem{instance=\"$instance\", name=\"IoTConsensus\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "IoTConsensus Sync Index",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"safeIndex\"}",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "IoTConsensus Overview",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"searchIndex\"}) by (instance) - sum(iot_consensus{name=\"ioTConsensusServerImpl\", type=\"safeIndex\"}) by (instance)",
       "legendFormat": "Total Sync Lag"
      },
      {
       "expr": "sum(iot_consensus{instance=~\"$instance\", type=~\"cachedRequestInMemoryQueue\"}) by (instance)",
       "legendFormat": "Cached Request"
      }
     ]
    },
    {
     "title": "The Time Consumed Of Different Stages (50%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(stage{quantile=\"0.5\", instance=~\"${instance}\"}) by (instance, type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The Time Consumed Of Different Stages (75%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(stage{quantile=\"0.75\", instance=~\"${instance}\"}) by (instance, type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "The Time Consumed Of Different Stages (100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(stage{quantile=\"1.0\", instance=~\"${instance}\"}) by (instance, type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "IoTConsensus Search Index Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "irate(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"searchIndex\"}[1m])",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "IoTConsensus Safe Index Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "irate(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"safeIndex\"}[1m])",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "IoTConsensus LogDispatcher Request Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(iot_consensus{instance=~\"$instance\", type=~\"cachedRequestInMemoryQueue\"}) by (region, name)",
       "legendFormat": "{{region}} {{name}}"
      }
     ]
    },
    {
     "title": "Sync Lag",
     "type": "timeseries",
     "description": "Total Sync Gap of region",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"searchIndex\"}) by (region) - sum(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"safeIndex\"}) by (region)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Min Peer Sync Lag",
     "type": "timeseries",
     "description": "Gap between write and fastest LogDispatcherThread in one region",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"searchIndex\"}) by (region) - max(iot_consensus{instance=~\"$instance\", name=~\"logDispatcher.*\", type=\"currentSyncIndex\"}) by (region)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Sync Speed Diff Of Peers",
     "type": "timeseries",
     "description": "Gap between fastest LogDispatcherThread and slowest LogDispatcherThread in one region",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(iot_consensus{instance=~\"$instance\", name=~\"logDispatcher.*\", type=\"currentSyncIndex\"}) by (region) - min(iot_consensus{instance=~\"$instance\", name=~\"logDispatcher.*\", type=\"currentSyncIndex\"}) by (region)",
       "legendFormat": "{{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Core",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Core" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sys_cpu_cores{instance=\"$instance\",name=\"system\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sys_cpu_load{instance=\"$instance\",name=\"system\"}",
       "legendFormat": "System CPU Load"
      },
      {
       "expr": "process_cpu_load{instance=\"$instance\",name=\"process\"}",
       "legendFormat": "Process CPU Load"
      }
     ]
    },
    {
     "title": "CPU Time(per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_time{instance=\"$instance\",name=\"process\"}[1m]))*60",
       "legendFormat": "System CPU Load"
      }
     ]
    },
    {
     "title": "System Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}-sys_free_physical_memory_size{instance=\"$instance\", name=\"system\"}",
       "legendFormat": "Used physical memory"
      },
      {
       "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
       "legendFormat": "Total physical memory"
      },
      {
       "expr": "sys_committed_vm_size{instance=\"$instance\"}",
       "legendFormat": "Committed vm size"
      }
     ]
    },
    {
     "title": "System Swap Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"} - sys_free_swap_space_size{instance=\"$instance\", name=\"system\"}",
       "legendFormat": "Used Swap Size"
      },
      {
       "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"}",
       "legendFormat": "Total Swap Size"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_max_mem{instance=~\"${instance}\"}",
       "legendFormat": "Max Memory"
      },
      {
       "expr": "process_total_mem{instance=~\"${instance}\"}",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "process_total_mem{instance=~\"${instance}\"} - process_free_mem{instance=~\"${instance}\"}",
       "legendFormat": "Used Memory"
      }
     ]
    },
    {
     "title": "The Size Of File",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "file_size{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(file_size{instance=~\"$instance\"})",
       "legendFormat": "total size of file"
      }
     ]
    },
    {
     "title": "The Number Of File",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "expr": "file_count{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(file_count{instance=~\"$instance\"})",
       "legendFormat": "total number of file"
      }
     ]
    },
    {
     "title": "The Space of Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sys_disk_total_space{instance=~\"$instance\", name=\"system\"}-sys_disk_free_space{instance=\"$instance\", name=\"system\"}",
       "legendFormat": "Used disk space"
      },
      {
       "expr": "sys_disk_total_space{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "Total disk space"
      }
     ]
    },
    {
     "title": "The Number of GC Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
       "legendFormat": "Young GC number"
      },
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
       "legendFormat": "Full GC number"
      }
     ]
    },
    {
     "title": "The Time Consumed Of GC Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
       "legendFormat": "The time of young GC"
      },
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
       "legendFormat": "The time of full GC"
      }
     ]
    },
    {
     "title": "The Number Of Java Thread",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
       "legendFormat": "The total number of jvm thread"
      },
      {
       "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Maximum heap memory"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Used heap memory"
      },
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Old Gen\"}",
       "legendFormat": "Old area"
      },
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Eden Space\"}",
       "legendFormat": "Eden area"
      },
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Survivor Space\"}",
       "legendFormat": "Survivor area"
      }
     ]
    },
    {
     "title": "Off Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{instance=~\"$instance\"})",
       "legendFormat": "off heap memory"
      }
     ]
    },
    {
     "title": "Log Number Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{instance=~\"${instance}\"}[1m])) by (level) * 60",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "The Time Consumed Of Compilation Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_compilation_time_ms{instance=~\"${instance}\"}[1m]))*60",
       "legendFormat": "compiler"
      }
     ]
    },
    {
     "title": "The Number Of Class",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_classes_unloaded_classes{instance=~\"$instance\"}",
       "legendFormat": "Unloaded Number"
      },
      {
       "expr": "jvm_classes_loaded_classes{instance=~\"$instance\"}",
       "legendFormat": "Loaded Number"
      }
     ]
    }
   ]
  }
 ]
}