{
 "title": "yesterday dashboard",
 "tags": [
  "Apache-IoTDB",
  "ConfigNode",
  "v1.0"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ConfigNode Current Status",
   "type": "piechart",
   "description": "The current status of cluster ConfigNodes",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_num{type=\"ConfigNode\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "description": "The CPU Core of current ConfigNode",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_cpu_cores{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "description": "The total disk space of current ConfigNode",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sys_disk_total_space", "legendFormat": "{{name}}" }
   ]
  },
  {
   "type": "bargauge",
   "description": "Bar of current ConfigNode",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_load{instance=~\"$instance\"} / 100",
     "legendFormat": "cpu load"
    },
    {
     "expr": "1- sys_disk_free_space / sys_disk_total_space",
     "legendFormat": "disk"
    },
    {
     "expr": "1 - process_free_mem{instance=\"$instance\"} / process_total_mem{instance=\"$instance\"}",
     "legendFormat": "process memory"
    },
    {
     "expr": "1 - sys_free_physical_memory_size{instance=\"$instance\", name=\"system\"} / sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "system memory"
    }
   ]
  },
  {
   "title": "DataNode Current Status",
   "type": "piechart",
   "description": "The current status of cluster DataNodes",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_num{type=\"DataNode\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "stat",
   "description": "The system memory of current ConfigNode",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "stat",
   "description": "The swap memory of current ConfigNode",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ConfigNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "ConfigNode Count",
     "type": "stat",
     "description": "The number of cluster ConfigNodes",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(type) (node_num{type=\"ConfigNode\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ConfigNode Status History",
     "type": "timeseries",
     "description": "The status history of cluster ConfigNodes",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 14 },
     "targets": [
      {
       "expr": "node_num{type=\"ConfigNode\"}",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DataNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "DataNode Count",
     "type": "stat",
     "description": "The number of cluster DataNodes",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(type) (node_num{type=\"DataNode\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DataNode Status",
     "type": "timeseries",
     "description": "The status of cluster DataNodes",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 21 },
     "targets": [
      {
       "expr": "node_num{type=\"DataNode\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "SchemaRegion Distribution",
     "type": "timeseries",
     "description": "The number of SchemaRegions in each DataNode",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "region_num_in_data_node{type=\"SchemaRegion\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "SchemaRegionGroup Leader Distribution",
     "type": "timeseries",
     "description": "The number of SchemaRegionGroup leadere in each DataNodes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "region_group_leader_num_in_data_node{type=\"SchemaRegion\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "DataRegion Distribution",
     "type": "timeseries",
     "description": "The number of DataRegions in each DataNode",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "region_num_in_data_node{type=\"DataRegion\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "DataRegionGroup Leader Distribution",
     "type": "timeseries",
     "description": "The number of DataRegionGroup leaders in each DataNode",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "region_num_in_data_node{type=\"DataRegion\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Count",
     "type": "stat",
     "description": "The number of cluster Databases",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "database_num", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "SeriesSlot Count",
     "type": "timeseries",
     "description": "The number of SeriesSlots in each Database",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 40 },
     "targets": [
      { "expr": "series_slot_num_in_database", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "SchemaRegionGroup Count",
     "type": "timeseries",
     "description": "The number of SchemaRegionGroups in each Database",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "region_group_num_in_database{type=\"SchemaRegion\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "DataRegionGroup Count",
     "type": "timeseries",
     "description": "The number of DataRegionGroups in each DataNode",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "region_group_num_in_database{type=\"DataRegion\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "SchemaRegion Count",
     "type": "stat",
     "description": "The number of cluster SchemaRegions",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(type) (region_num{type=\"SchemaRegion\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SchemaRegion Current Status",
     "type": "piechart",
     "description": "The current status of cluster SchemaRegions",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "region_num{type=\"SchemaRegion\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "SchemaRegion Status History",
     "type": "timeseries",
     "description": "The status history of cluster SchemaRegions",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "region_num{type=\"SchemaRegion\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "DataRegion Count",
     "type": "stat",
     "description": "The number of cluster DataRegions",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (type) (region_num{type=\"DataRegion\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DataRegion Current Status",
     "type": "piechart",
     "description": "The current status of cluster DataRegions",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "region_num{type=\"DataRegion\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "DataRegion Status History",
     "type": "timeseries",
     "description": "The status history of cluster DataRegions",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "region_num{type=\"DataRegion\"}",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Core",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "Core" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sys_cpu_cores{instance=\"$instance\",name=\"system\"}",
       "legendFormat": "Process CPU Time"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sys_cpu_load{instance=\"$instance\",name=\"system\"}",
       "legendFormat": "System CPU Load"
      },
      {
       "expr": "process_cpu_load{instance=\"$instance\",name=\"process\"}",
       "legendFormat": "Process CPU Load"
      }
     ]
    },
    {
     "title": "CPU Time Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_time{instance=\"$instance\",name=\"process\"}[1m]))*60",
       "legendFormat": "Process CPU Time"
      }
     ]
    },
    {
     "title": "System Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}-sys_free_physical_memory_size{instance=\"$instance\", name=\"system\"}",
       "legendFormat": "Used physical memory"
      },
      {
       "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
       "legendFormat": "Total physical memory"
      },
      {
       "expr": "sys_committed_vm_size{instance=\"$instance\"}",
       "legendFormat": "Committed vm size"
      }
     ]
    },
    {
     "title": "System Swap Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"} - sys_free_swap_space_size{instance=\"$instance\", name=\"system\"}",
       "legendFormat": "Used Swap Size"
      },
      {
       "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"}",
       "legendFormat": "Total Swap Size"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_max_mem{instance=~\"${instance}\"}",
       "legendFormat": "Max Memory"
      },
      {
       "expr": "process_total_mem{instance=~\"${instance}\"}",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "process_total_mem{instance=~\"${instance}\"} - process_free_mem{instance=~\"${instance}\"}",
       "legendFormat": "Used Memory"
      }
     ]
    },
    {
     "title": "The Number Of GC Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 120 },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
       "legendFormat": "Young GC number"
      },
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
       "legendFormat": "Full GC number"
      }
     ]
    },
    {
     "title": "The Time Consumed Of GC Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
       "legendFormat": "The time of young GC"
      },
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
       "legendFormat": "The time of full GC"
      }
     ]
    },
    {
     "title": "The Number Of Java Thread",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 120 },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
       "legendFormat": "Total Number"
      },
      {
       "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Maximum heap memory"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Used heap memory"
      },
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Old Gen\"}",
       "legendFormat": "Old area"
      },
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Eden Space\"}",
       "legendFormat": "Eden area"
      },
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Survivor Space\"}",
       "legendFormat": "Survivor area"
      }
     ]
    },
    {
     "title": "Off Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{instance=~\"$instance\"})",
       "legendFormat": "off-heap memory"
      }
     ]
    },
    {
     "title": "Log Number Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{instance=~\"${instance}\"}[1m])) by (level) * 60",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "The Time Consumed of Compilation Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_compilation_time_ms{instance=~\"${instance}\"}[1m]))*60",
       "legendFormat": "compiler"
      }
     ]
    },
    {
     "title": "The  Number Of Class",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
     "targets": [
      {
       "expr": "jvm_classes_unloaded_classes{instance=~\"$instance\"}",
       "legendFormat": "Unloaded Number"
      },
      {
       "expr": "jvm_classes_loaded_classes{instance=~\"$instance\"}",
       "legendFormat": "Loaded Number"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk I/O Busy Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "disk_io_busy_percentage{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk I/O Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rate(disk_io_size{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{name}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(disk_io_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{name}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(disk_io_time{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{name}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk Per I/O Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_io_avg_time{instance=~\"$instance\"}",
       "legendFormat": "{{name}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Avg Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_io_avg_size{instance=~\"$instance\"}",
       "legendFormat": "{{name}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Avg Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 121 },
     "targets": [
      {
       "expr": "disk_io_avg_queue_size{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Process I/O Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rate(process_io_size{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{from}}-{{name}}"
      }
     ]
    },
    {
     "title": "I/O System Call Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(process_io_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{from}}-{{name}}"
      }
     ]
    }
   ]
  }
 ]
}