#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# docker build context is the root path of the repository

FROM openjdk:11-jre-slim

ADD distribution/target/apache-iotdb-*-confignode-bin.zip /

RUN apt update \
  && apt install lsof dos2unix procps unzip -y \
  && unzip /apache-iotdb-*-bin.zip -d / \
  && rm /apache-iotdb-*-bin.zip \
  && mv /apache-iotdb-* /confignode \
  && apt remove unzip -y \
  && apt autoremove -y \
  && apt purge --auto-remove -y \
  && apt clean -y
RUN dos2unix /confignode/sbin/start-confignode.sh
RUN dos2unix /confignode/sbin/../conf/confignode-env.sh
EXPOSE 22278
EXPOSE 22277
VOLUME /confignode/data
VOLUME /confignode/logs
ENV PATH="/datanode/sbin/:${PATH}"
ENTRYPOINT ["/confignode/sbin/start-confignode.sh"]
