-- ============================================================
-- Plan Cache 功能测试脚本 (IoTDB 表模型)
-- ============================================================
-- 使用方式: 在 IoTDB CLI 中以表模式连接后逐段执行
--   ./start-cli.sh -h 127.0.0.1 -p 6667 -u root -pw root --sql_dialect table
-- ============================================================

-- 1. 创建数据库
CREATE DATABASE IF NOT EXISTS test_plan_cache;
USE test_plan_cache;

-- 2. 创建表：2 个 TAG 列 + 80 个 FIELD 列
CREATE TABLE sensor_data (
  region    STRING TAG,
  device_id STRING TAG,
  f_00 DOUBLE FIELD, f_01 DOUBLE FIELD, f_02 DOUBLE FIELD, f_03 DOUBLE FIELD, f_04 DOUBLE FIELD,
  f_05 DOUBLE FIELD, f_06 DOUBLE FIELD, f_07 DOUBLE FIELD, f_08 DOUBLE FIELD, f_09 DOUBLE FIELD,
  f_10 DOUBLE FIELD, f_11 DOUBLE FIELD, f_12 DOUBLE FIELD, f_13 DOUBLE FIELD, f_14 DOUBLE FIELD,
  f_15 DOUBLE FIELD, f_16 DOUBLE FIELD, f_17 DOUBLE FIELD, f_18 DOUBLE FIELD, f_19 DOUBLE FIELD,
  f_20 DOUBLE FIELD, f_21 DOUBLE FIELD, f_22 DOUBLE FIELD, f_23 DOUBLE FIELD, f_24 DOUBLE FIELD,
  f_25 DOUBLE FIELD, f_26 DOUBLE FIELD, f_27 DOUBLE FIELD, f_28 DOUBLE FIELD, f_29 DOUBLE FIELD,
  f_30 DOUBLE FIELD, f_31 DOUBLE FIELD, f_32 DOUBLE FIELD, f_33 DOUBLE FIELD, f_34 DOUBLE FIELD,
  f_35 DOUBLE FIELD, f_36 DOUBLE FIELD, f_37 DOUBLE FIELD, f_38 DOUBLE FIELD, f_39 DOUBLE FIELD,
  f_40 DOUBLE FIELD, f_41 DOUBLE FIELD, f_42 DOUBLE FIELD, f_43 DOUBLE FIELD, f_44 DOUBLE FIELD,
  f_45 DOUBLE FIELD, f_46 DOUBLE FIELD, f_47 DOUBLE FIELD, f_48 DOUBLE FIELD, f_49 DOUBLE FIELD,
  f_50 DOUBLE FIELD, f_51 DOUBLE FIELD, f_52 DOUBLE FIELD, f_53 DOUBLE FIELD, f_54 DOUBLE FIELD,
  f_55 DOUBLE FIELD, f_56 DOUBLE FIELD, f_57 DOUBLE FIELD, f_58 DOUBLE FIELD, f_59 DOUBLE FIELD,
  f_60 DOUBLE FIELD, f_61 DOUBLE FIELD, f_62 DOUBLE FIELD, f_63 DOUBLE FIELD, f_64 DOUBLE FIELD,
  f_65 DOUBLE FIELD, f_66 DOUBLE FIELD, f_67 DOUBLE FIELD, f_68 DOUBLE FIELD, f_69 DOUBLE FIELD,
  f_70 DOUBLE FIELD, f_71 DOUBLE FIELD, f_72 DOUBLE FIELD, f_73 DOUBLE FIELD, f_74 DOUBLE FIELD,
  f_75 DOUBLE FIELD, f_76 DOUBLE FIELD, f_77 DOUBLE FIELD, f_78 DOUBLE FIELD, f_79 DOUBLE FIELD
);
