version: "3.7"

services:
  grafana:
    image: grafana/grafana:8.0.5
    volumes:
      - ./dist:/var/lib/grafana/plugins/dist
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000

  iotdb:
    image: apache/iotdb0.14
    build:
      context: ./     
      dockerfile: Dockerfile-0.14.0-iotdb       
    volumes:
      - ./iotdb/conf/iotdb-rest.properties:/iotdb/conf/iotdb-rest.properties
      - ./iotdb/data/:/iotdb/data
    ports: 
      - 6667:6667
      - 18080:18080
      - 5555:5555
      - 31999:31999
      - 8181:8181
  alertmanager:
      image: prom/alertmanager:v0.21.0
      ports:
        - 9093:9093

