# default config for createTrainingTask

# data config
---
source_type: file
filename: dataset/ETT-small/ETTh1.csv
query_expressions: ['root.eg.etth1.s0', 'root.eg.etth1.s1']
query_filter: '-1,1501516800000'
dataset_type: window
time_embed: h
input_len: 96
pred_len: 96
input_vars: 7
output_vars: 7

# model config
---
model_name: dlinear
input_len: 96
pred_len: 96
input_vars: 7
output_vars: 7
task_type: m
kernel_size: 25
block_type: g
d_model: 128
inner_layers: 4
outer_layers: 4

# task config
---
model_id: mid_test
tuning: False
task_type: m
task_class: forecast_training_task
input_len: 96
pred_len: 96
input_vars: 7
output_vars: 7
learning_rate: 0.0001
batch_size: 32
num_workers: 0
epochs: 10
use_gpu: False
gpu: 0
use_multi_gpu: False
devices: [0]
metric_names: [MSE, MAE]
