version: "2"

services:
    iotdb:
      image: apache/iotdb
      ports:
        - 6667:6667
      container_name: "iotdb"
    grafana:
      image: grafana/grafana
      ports:
        - 3000:3000
      environment:
        - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
      container_name: "grafana"
    grafana-connector:
      image: apache/iotdb:0.12.2-grafana
      environment:
        - SPRING_DATASOURCE_URL=jdbc:iotdb://iotdb:6667/
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.apache.iotdb.jdbc.IoTDBDriver
        - SERVER_PORT=8888
        - TIMESTAMP_PRECISION=ms
        - ISDOWNSAMPLING=true
        - INTERVAL=1m
        - CONTINUOUS_DATA_FUNCTION=AVG
        - DISCRETE_DATA_FUNCTION=LAST_VALUE
      ports:
        - 8888:8888
      container_name: "grafana-connector"
