### model
model_type: timer_xl
seq_len: 672
input_token_len: 96
output_token_lens:
  - 96

### method
finetune_type: lora
lora_rank: 2
lora_alpha: 8
lora_dropout: 0.1
lora_target_modules:
  - q_proj
  - v_proj

### dataset
dataset_type: csv
data_path: /path/to/ETTh1.csv

### training
num_train_epochs: 20
train_batch_size: 64
learning_rate: 5.0e-6
scheduler_type: cosine
use_amp: true
