/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.iotdb.consensus.natraft.protocol.log.dispatch.flowcontrol;

import org.apache.iotdb.common.rpc.thrift.TEndPoint;
import org.apache.iotdb.consensus.natraft.protocol.RaftConfig;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FlowMonitor {

  private static final Logger logger = LoggerFactory.getLogger(FlowMonitor.class);
  private static final String FILE_SUFFIX = ".flow";
  private ArrayDeque<FlowWindow> windows;
  private long currWindowStart;
  private long currWindowSum;
  private long windowInterval;
  private TEndPoint node;
  private int maxWindowSize;
  private BufferedWriter writer;
  private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
  private RaftConfig config;
  private boolean recordFlow = false;

  public FlowMonitor(TEndPoint node, RaftConfig config) throws IOException {
    this.maxWindowSize = config.getFlowMonitorMaxWindowNum();
    this.windows = new ArrayDeque<>(maxWindowSize);
    this.windowInterval = config.getFlowMonitorWindowInterval();
    this.node = node;
    this.config = config;
    initSerializer();
  }

  private void initSerializer() throws IOException {
    String path =
        config.getStorageDir() + File.separator + node.getIp() + "-" + node.getPort() + FILE_SUFFIX;
    File file = new File(path);
    file.delete();
    if (recordFlow) {
      writer = new BufferedWriter(new FileWriter(file));
      writer.write("Time,FlowSum");
      writer.newLine();
    }
  }

  public void close() {
    saveWindow();
    while (windows.size() > 0) {
      serializeWindow();
    }
    if (writer != null) {
      try {
        writer.close();
        logger.info("Flow monitor {} is closed", node);
      } catch (IOException e) {
        logger.warn("Cannot close serializer of {}", node, e);
      }
    }
  }

  private void resetWindow(long newWindowStart) {
    currWindowStart = newWindowStart;
    currWindowSum = 0;
  }

  private void serializeWindow() {
    FlowWindow window = windows.removeFirst();
    if (writer != null) {
      try {
        String windowString =
            String.format("%s,%d", dateFormat.format(new Date(window.start)), window.sum);
        logger.debug("New window {} serialized by {}", windowString, node);
        writer.write(windowString);
        writer.newLine();
      } catch (IOException e) {
        logger.warn("Cannot serialize window {} of {}", window, node, e);
      }
    }
  }

  private void checkSize() {
    if (windows.size() == maxWindowSize) {
      serializeWindow();
    }
  }

  private void saveWindow() {
    if (currWindowSum != 0) {
      checkSize();
      windows.add(new FlowWindow(currWindowStart, currWindowSum));
      logger.debug("New window {},{} generated by {}", currWindowStart, currWindowSum, node);
    }
  }

  public synchronized void report(long val) {
    long currTime = System.currentTimeMillis();
    long targetWindowStart = currTime - currTime % windowInterval;
    if (targetWindowStart != currWindowStart) {
      // save the current window and start a new window
      saveWindow();
      resetWindow(targetWindowStart);
    }
    // update the current window
    currWindowSum += val;
  }

  public double averageFlow(int windowsToUse) {
    long flowSum = currWindowSum;
    long intervalSum = System.currentTimeMillis() - currWindowStart;
    if (intervalSum > windowInterval) {
      intervalSum = windowInterval;
    }

    Iterator<FlowWindow> windowIterator = windows.descendingIterator();
    for (int i = 1; i < windowsToUse; i++) {
      if (windowIterator.hasNext()) {
        FlowWindow window = windowIterator.next();
        flowSum += window.sum;
        intervalSum += windowInterval;
      } else {
        break;
      }
    }
    return flowSum * 1.0 / intervalSum * 1000;
  }

  public List<FlowWindow> getLatestWindows(int windowNum) {
    List<FlowWindow> result = new ArrayList<>();
    result.add(new FlowWindow(currWindowStart, currWindowSum));
    Iterator<FlowWindow> windowIterator = windows.descendingIterator();
    for (int i = 1; i < windowNum; i++) {
      if (windowIterator.hasNext()) {
        FlowWindow window = windowIterator.next();
        result.add(window);
      } else {
        break;
      }
    }
    return result;
  }
}
