{
 "title": "Apache IoTDB ConfigNode Dashboard",
 "tags": [
  "Apache-IoTDB",
  "ConfigNode",
  "0.14.0"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "config_node{instance=~\"$instance\"}",
     "legendFormat": "Online ConfigNode"
    },
    {
     "expr": "data_node{instance=~\"$instance\"}",
     "legendFormat": "Online DataNode"
    },
    {
     "expr": "storage_group{instance=~\"$instance\"}",
     "legendFormat": "Storage Group"
    },
    {
     "expr": "sum(region{instance=~\"$instance\", name=\"total\"})",
     "legendFormat": "Total Region"
    },
    {
     "expr": "region{instance=~\"$instance\", name=\"total\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total number of online nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "config_node{status=\"Online\"}",
     "legendFormat": "ConfigNode"
    },
    {
     "expr": "data_node{status=\"Online\"}",
     "legendFormat": "DataNode"
    }
   ]
  },
  {
   "title": "Total number of offline nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "config_node{status=\"Unknown\"}",
     "legendFormat": "ConfigNode"
    },
    {
     "expr": "data_node{status=\"Unknown\"}",
     "legendFormat": "DataNode"
    }
   ]
  },
  {
   "title": "Select the node that you want to view",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "cluster_node_status{name =~ \"EndPoint.*\"}",
     "legendFormat": "{{instance}}  {{type}} {{name}}"
    }
   ]
  },
  { "title": "Leadership Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Leadership distribution",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_node_leader_count{name =~ \"EndPoint.*\"}",
     "legendFormat": "{{name}} total leaders"
    }
   ]
  },
  { "title": "Region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Region in Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(region{instance=~\"${instance}\", name=~\"EndPoint.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Region in Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "region{instance=~\"${instance}\", name=~\"EndPoint.*\"}",
     "legendFormat": "{{name}}-{{type}}"
    }
   ]
  },
  {
   "title": "Region in StorageGroup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "region{instance=~\"${instance}\", name!=\"total\", name!~\"EndPoint.*\"}",
     "legendFormat": "{{name}}-{{type}}"
    }
   ]
  },
  {
   "title": "Slot In Storage Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "slot{instance=~\"$instance\"}",
     "legendFormat": "{{name}}-{{type}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "The number of GC (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
     "legendFormat": "Young GC number"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
     "legendFormat": "Full GC number"
    }
   ]
  },
  {
   "title": "The time consumed of GC(per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
     "legendFormat": "The time of young GC"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
     "legendFormat": "The time of full GC"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Maximum heap memory"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Used heap memory"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Old Gen\"}",
     "legendFormat": "Old area"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Eden Space\"}",
     "legendFormat": "Eden area"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Survivor Space\"}",
     "legendFormat": "Survivor area"
    }
   ]
  },
  {
   "title": "Off-heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_buffer_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "off-heap memory"
    }
   ]
  },
  {
   "title": "The number of Java thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
     "legendFormat": "The total number of jvm thread"
    },
    {
     "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "The time consumed of interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(entry_seconds_sum{}[1m])/rate(entry_seconds_count{}[1m])) by (name,instance)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "CPU-Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu_load{instance=\"$instance\",name=\"system\"}",
     "legendFormat": "System CPU Load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}-sys_free_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Used physical memory"
    },
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Total physical memory"
    }
   ]
  },
  {
   "title": "Disk-Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_disk_total_space{instance=\"$instance\", name=\"system\"}-sys_disk_free_space{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Used disk space"
    },
    {
     "expr": "sys_disk_total_space{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Total disk space"
    }
   ]
  }
 ]
}