{
 "title": "Apache IoTDB ConfigNode Dashboard",
 "tags": [
  "Apache-IoTDB",
  "ConfigNode",
  "v1.0"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registered Node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "config_node{instance=~\"$instance\", status=\"Registered\"}",
     "legendFormat": "ConfigNode"
    },
    {
     "expr": "data_node{instance=~\"$instance\", status=\"Registered\"}",
     "legendFormat": "DataNode"
    }
   ]
  },
  {
   "title": "DataNode",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "data_node{instance=~\"$instance\", status!=\"Registered\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "ConfigNode",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "config_node{instance=~\"$instance\", status!=\"Registered\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "The Status Of Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "cluster_node_status{instance=~\"${instance}\"}",
     "legendFormat": "{{type}} {{name}}"
    }
   ]
  },
  {
   "title": "Region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Region Number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(region{instance=~\"$instance\", name=\"total\"})",
     "legendFormat": "Total Region"
    },
    {
     "expr": "region{instance=~\"$instance\", name=\"total\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Leadership Distribution",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cluster_node_leader_count{}) by (name) ",
     "legendFormat": "Total leaders on {{name}} "
    }
   ]
  },
  {
   "title": "Total Region in Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(region{instance=~\"${instance}\", name=~\"EndPoint.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Region in Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "region{instance=~\"${instance}\", name=~\"EndPoint.*\"}",
     "legendFormat": "{{name}}-{{type}}"
    }
   ]
  },
  {
   "title": "Region in Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "region{instance=~\"${instance}\", name!=\"total\", name!~\"EndPoint.*\"}",
     "legendFormat": "{{name}}-{{type}}"
    }
   ]
  },
  {
   "title": "Slot In Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "slot{instance=~\"$instance\"}",
     "legendFormat": "{{name}}-{{type}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_cpu_cores{instance=\"$instance\",name=\"system\"}",
     "legendFormat": "Process CPU Time"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu_load{instance=\"$instance\",name=\"system\"}",
     "legendFormat": "System CPU Load"
    },
    {
     "expr": "process_cpu_load{instance=\"$instance\",name=\"process\"}",
     "legendFormat": "Process CPU Load"
    }
   ]
  },
  {
   "title": "CPU Time Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time{instance=\"$instance\",name=\"process\"}[1m]))*60",
     "legendFormat": "Process CPU Time"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}-sys_free_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Used physical memory"
    },
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Total physical memory"
    },
    {
     "expr": "sys_committed_vm_size{instance=\"$instance\"}",
     "legendFormat": "Committed vm size"
    }
   ]
  },
  {
   "title": "System Swap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"} - sys_free_swap_space_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Used Swap Size"
    },
    {
     "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Total Swap Size"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_max_mem{instance=~\"${instance}\"}",
     "legendFormat": "Max Memory"
    },
    {
     "expr": "process_total_mem{instance=~\"${instance}\"}",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "process_total_mem{instance=~\"${instance}\"} - process_free_mem{instance=~\"${instance}\"}",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "The Number Of GC Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
     "legendFormat": "Young GC number"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
     "legendFormat": "Full GC number"
    }
   ]
  },
  {
   "title": "The Time Consumed Of GC Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
     "legendFormat": "The time of young GC"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
     "legendFormat": "The time of full GC"
    }
   ]
  },
  {
   "title": "The Number Of Java Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
     "legendFormat": "Total Number"
    },
    {
     "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Maximum heap memory"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Used heap memory"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Old Gen\"}",
     "legendFormat": "Old area"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Eden Space\"}",
     "legendFormat": "Eden area"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Survivor Space\"}",
     "legendFormat": "Survivor area"
    }
   ]
  },
  {
   "title": "Off Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_buffer_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "off-heap memory"
    }
   ]
  },
  {
   "title": "Log Number Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{instance=~\"${instance}\"}[1m])) by (level) * 60",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "The Time Consumed of Compilation Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_compilation_time_ms{instance=~\"${instance}\"}[1m]))*60",
     "legendFormat": "compiler"
    }
   ]
  },
  {
   "title": "The  Number Of Class",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "jvm_classes_unloaded_classes{instance=~\"$instance\"}",
     "legendFormat": "Unloaded Number"
    },
    {
     "expr": "jvm_classes_loaded_classes{instance=~\"$instance\"}",
     "legendFormat": "Loaded Number"
    }
   ]
  }
 ]
}