{
 "title": "Apache IoTDB DataNode Dashboard",
 "tags": [
  "Apache-IoTDB",
  "DataNode",
  "v1.0"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "The Number Of Entity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "quantity{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Write Point Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(quantity_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "write point per second"
    }
   ]
  },
  {
   "title": "Database Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem{instance=~\"$instance\", name!=\"IoTConsensus\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "The Time Consumed Of Operation (50%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "operation{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "The Time Consumed Of Operation (75%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "operation{instance=~\"$instance\", quantile=\"0.75\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "The Time Consumed Of Operation (100%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "operation{instance=~\"$instance\", quantile=\"1.0\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "The QPS Of Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(entry_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "The Time Consumed Of Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(rate(entry_seconds_sum{instance=~\"$instance\"}[1m])/rate(entry_seconds_count{instance=~\"$instance\"}[1m])) by (name,instance)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(cache_total{instance=~\"$instance\", type=\"hit\"}) by (name) / avg(cache_total{instance=~\"$instance\", type=\"all\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "cache_hit{instance=~\"$instance\"} / 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thrift Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "thrift_connections{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thrift Active Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "thrift_active_threads{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "queue{instance=~\"$instance\"}",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "The Time Consumed of Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(cost_task_seconds_sum{instance=~\"$instance\"}[1m])/rate(cost_task_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Compaction Read And Write Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(data_written_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(data_read_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Compaction R/W Ratio Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(data_read_total{instance=~\"$instance\"}[1m]))*60 / sum(rate(data_written_total{instance=~\"$instance\"}[1m]))*60",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Compaction Number Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(compaction_task_count_total{instance=\"$instance\", name = \"inner_compaction\", type=\"sequence\"}[1m]))*60",
     "legendFormat": "sequence"
    },
    {
     "expr": "sum(rate(compaction_task_count_total{instance=\"$instance\", name = \"inner_compaction\", type=\"unsequence\"}[1m]))*60",
     "legendFormat": "unsequence"
    },
    {
     "expr": "sum(rate(compaction_task_count_total{instance=\"$instance\", name = \"cross_compaction\", type=\"cross\"}[1m]))*60",
     "legendFormat": "cross"
    }
   ]
  },
  {
   "title": "IoT Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IoTConsensus Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem{instance=\"$instance\", name=\"IoTConsensus\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IoTConsensus Sync Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"safeIndex\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "IoTConsensus Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"searchIndex\"}) by (instance) - sum(iot_consensus{name=\"ioTConsensusServerImpl\", type=\"safeIndex\"}) by (instance)",
     "legendFormat": "Total Sync Lag"
    },
    {
     "expr": "sum(iot_consensus{instance=~\"$instance\", type=~\"cachedRequestInMemoryQueue\"}) by (instance)",
     "legendFormat": "Cached Request"
    }
   ]
  },
  {
   "title": "The Time Consumed Of Different Stages (50%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(stage{quantile=\"0.5\", instance=~\"${instance}\"}) by (instance, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "The Time Consumed Of Different Stages (75%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(stage{quantile=\"0.75\", instance=~\"${instance}\"}) by (instance, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "The Time Consumed Of Different Stages (100%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(stage{quantile=\"1.0\", instance=~\"${instance}\"}) by (instance, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "IoTConsensus Search Index Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "irate(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"searchIndex\"}[1m])",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "IoTConsensus Safe Index Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "expr": "irate(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"safeIndex\"}[1m])",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "IoTConsensus LogDispatcher Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(iot_consensus{instance=~\"$instance\", type=~\"cachedRequestInMemoryQueue\"}) by (region, name)",
     "legendFormat": "{{region}} {{name}}"
    }
   ]
  },
  {
   "title": "Sync Lag",
   "type": "timeseries",
   "description": "Total Sync Gap of region",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"searchIndex\"}) by (region) - sum(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"safeIndex\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Min Peer Sync Lag",
   "type": "timeseries",
   "description": "Gap between write and fastest LogDispatcherThread in one region",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(iot_consensus{instance=~\"$instance\", name=\"ioTConsensusServerImpl\", type=\"searchIndex\"}) by (region) - max(iot_consensus{instance=~\"$instance\", name=~\"logDispatcher.*\", type=\"currentSyncIndex\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Sync Speed Diff Of Peers",
   "type": "timeseries",
   "description": "Gap between fastest LogDispatcherThread and slowest LogDispatcherThread in one region",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(iot_consensus{instance=~\"$instance\", name=~\"logDispatcher.*\", type=\"currentSyncIndex\"}) by (region) - min(iot_consensus{instance=~\"$instance\", name=~\"logDispatcher.*\", type=\"currentSyncIndex\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_cpu_cores{instance=\"$instance\",name=\"system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu_load{instance=\"$instance\",name=\"system\"}",
     "legendFormat": "System CPU Load"
    },
    {
     "expr": "process_cpu_load{instance=\"$instance\",name=\"process\"}",
     "legendFormat": "Process CPU Load"
    }
   ]
  },
  {
   "title": "CPU Time(per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time{instance=\"$instance\",name=\"process\"}[1m]))*60",
     "legendFormat": "System CPU Load"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}-sys_free_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Used physical memory"
    },
    {
     "expr": "sys_total_physical_memory_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Total physical memory"
    },
    {
     "expr": "sys_committed_vm_size{instance=\"$instance\"}",
     "legendFormat": "Committed vm size"
    }
   ]
  },
  {
   "title": "System Swap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"} - sys_free_swap_space_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Used Swap Size"
    },
    {
     "expr": "sys_total_swap_space_size{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Total Swap Size"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_max_mem{instance=~\"${instance}\"}",
     "legendFormat": "Max Memory"
    },
    {
     "expr": "process_total_mem{instance=~\"${instance}\"}",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "process_total_mem{instance=~\"${instance}\"} - process_free_mem{instance=~\"${instance}\"}",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "The Size Of File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "file_size{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(file_size{instance=~\"$instance\"})",
     "legendFormat": "total size of file"
    }
   ]
  },
  {
   "title": "The Number Of File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "targets": [
    {
     "expr": "file_count{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(file_count{instance=~\"$instance\"})",
     "legendFormat": "total number of file"
    }
   ]
  },
  {
   "title": "The Space of Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_disk_total_space{instance=~\"$instance\", name=\"system\"}-sys_disk_free_space{instance=\"$instance\", name=\"system\"}",
     "legendFormat": "Used disk space"
    },
    {
     "expr": "sys_disk_total_space{instance=~\"$instance\", name=\"system\"}",
     "legendFormat": "Total disk space"
    }
   ]
  },
  {
   "title": "The Number of GC Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
     "legendFormat": "Young GC number"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
     "legendFormat": "Full GC number"
    }
   ]
  },
  {
   "title": "The Time Consumed Of GC Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
     "legendFormat": "The time of young GC"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
     "legendFormat": "The time of full GC"
    }
   ]
  },
  {
   "title": "The Number Of Java Thread",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 109 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
     "legendFormat": "The total number of jvm thread"
    },
    {
     "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Maximum heap memory"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "Used heap memory"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Old Gen\"}",
     "legendFormat": "Old area"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Eden Space\"}",
     "legendFormat": "Eden area"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\",id=\"PS Survivor Space\"}",
     "legendFormat": "Survivor area"
    }
   ]
  },
  {
   "title": "Off Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_buffer_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "off heap memory"
    }
   ]
  },
  {
   "title": "Log Number Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{instance=~\"${instance}\"}[1m])) by (level) * 60",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "The Time Consumed Of Compilation Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_compilation_time_ms{instance=~\"${instance}\"}[1m]))*60",
     "legendFormat": "compiler"
    }
   ]
  },
  {
   "title": "The Number Of Class",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_classes_unloaded_classes{instance=~\"$instance\"}",
     "legendFormat": "Unloaded Number"
    },
    {
     "expr": "jvm_classes_loaded_classes{instance=~\"$instance\"}",
     "legendFormat": "Loaded Number"
    }
   ]
  }
 ]
}