package org.apache.iotdb.db.qp.strategy;

public enum StatementType {
  AUTHOR_STATEMENT,
  DELETE_STATEMENT,
  UPDATE_STATEMENT,
  INSERT_STATEMENT,
  QUERY_STATEMENT,
  METADATA_STATEMENT,
  MERGE_STATEMENT,
  INDEX_STATEMENT,
  QUIT_STATEMENT,
  LIST_STATEMENT
}
