/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.iotdb.service.rpc.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2025-05-09")
public class TSRawDataQueryReq implements org.apache.thrift.TBase<TSRawDataQueryReq, TSRawDataQueryReq._Fields>, java.io.Serializable, Cloneable, Comparable<TSRawDataQueryReq> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TSRawDataQueryReq");

  private static final org.apache.thrift.protocol.TField SESSION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("sessionId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField PATHS_FIELD_DESC = new org.apache.thrift.protocol.TField("paths", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField FETCH_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("fetchSize", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField START_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("startTime", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField END_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("endTime", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField STATEMENT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("statementId", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField ENABLE_REDIRECT_QUERY_FIELD_DESC = new org.apache.thrift.protocol.TField("enableRedirectQuery", org.apache.thrift.protocol.TType.BOOL, (short)7);
  private static final org.apache.thrift.protocol.TField JDBC_QUERY_FIELD_DESC = new org.apache.thrift.protocol.TField("jdbcQuery", org.apache.thrift.protocol.TType.BOOL, (short)8);
  private static final org.apache.thrift.protocol.TField TIMEOUT_FIELD_DESC = new org.apache.thrift.protocol.TField("timeout", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField LEGAL_PATH_NODES_FIELD_DESC = new org.apache.thrift.protocol.TField("legalPathNodes", org.apache.thrift.protocol.TType.BOOL, (short)10);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TSRawDataQueryReqStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TSRawDataQueryReqTupleSchemeFactory();

  public long sessionId; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> paths; // required
  public int fetchSize; // optional
  public long startTime; // required
  public long endTime; // required
  public long statementId; // required
  public boolean enableRedirectQuery; // optional
  public boolean jdbcQuery; // optional
  public long timeout; // optional
  public boolean legalPathNodes; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SESSION_ID((short)1, "sessionId"),
    PATHS((short)2, "paths"),
    FETCH_SIZE((short)3, "fetchSize"),
    START_TIME((short)4, "startTime"),
    END_TIME((short)5, "endTime"),
    STATEMENT_ID((short)6, "statementId"),
    ENABLE_REDIRECT_QUERY((short)7, "enableRedirectQuery"),
    JDBC_QUERY((short)8, "jdbcQuery"),
    TIMEOUT((short)9, "timeout"),
    LEGAL_PATH_NODES((short)10, "legalPathNodes");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SESSION_ID
          return SESSION_ID;
        case 2: // PATHS
          return PATHS;
        case 3: // FETCH_SIZE
          return FETCH_SIZE;
        case 4: // START_TIME
          return START_TIME;
        case 5: // END_TIME
          return END_TIME;
        case 6: // STATEMENT_ID
          return STATEMENT_ID;
        case 7: // ENABLE_REDIRECT_QUERY
          return ENABLE_REDIRECT_QUERY;
        case 8: // JDBC_QUERY
          return JDBC_QUERY;
        case 9: // TIMEOUT
          return TIMEOUT;
        case 10: // LEGAL_PATH_NODES
          return LEGAL_PATH_NODES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SESSIONID_ISSET_ID = 0;
  private static final int __FETCHSIZE_ISSET_ID = 1;
  private static final int __STARTTIME_ISSET_ID = 2;
  private static final int __ENDTIME_ISSET_ID = 3;
  private static final int __STATEMENTID_ISSET_ID = 4;
  private static final int __ENABLEREDIRECTQUERY_ISSET_ID = 5;
  private static final int __JDBCQUERY_ISSET_ID = 6;
  private static final int __TIMEOUT_ISSET_ID = 7;
  private static final int __LEGALPATHNODES_ISSET_ID = 8;
  private short __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.FETCH_SIZE,_Fields.ENABLE_REDIRECT_QUERY,_Fields.JDBC_QUERY,_Fields.TIMEOUT,_Fields.LEGAL_PATH_NODES};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SESSION_ID, new org.apache.thrift.meta_data.FieldMetaData("sessionId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PATHS, new org.apache.thrift.meta_data.FieldMetaData("paths", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.FETCH_SIZE, new org.apache.thrift.meta_data.FieldMetaData("fetchSize", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.START_TIME, new org.apache.thrift.meta_data.FieldMetaData("startTime", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.END_TIME, new org.apache.thrift.meta_data.FieldMetaData("endTime", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.STATEMENT_ID, new org.apache.thrift.meta_data.FieldMetaData("statementId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ENABLE_REDIRECT_QUERY, new org.apache.thrift.meta_data.FieldMetaData("enableRedirectQuery", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.JDBC_QUERY, new org.apache.thrift.meta_data.FieldMetaData("jdbcQuery", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.TIMEOUT, new org.apache.thrift.meta_data.FieldMetaData("timeout", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LEGAL_PATH_NODES, new org.apache.thrift.meta_data.FieldMetaData("legalPathNodes", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TSRawDataQueryReq.class, metaDataMap);
  }

  public TSRawDataQueryReq() {
  }

  public TSRawDataQueryReq(
    long sessionId,
    java.util.List<java.lang.String> paths,
    long startTime,
    long endTime,
    long statementId)
  {
    this();
    this.sessionId = sessionId;
    setSessionIdIsSet(true);
    this.paths = paths;
    this.startTime = startTime;
    setStartTimeIsSet(true);
    this.endTime = endTime;
    setEndTimeIsSet(true);
    this.statementId = statementId;
    setStatementIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TSRawDataQueryReq(TSRawDataQueryReq other) {
    __isset_bitfield = other.__isset_bitfield;
    this.sessionId = other.sessionId;
    if (other.isSetPaths()) {
      java.util.List<java.lang.String> __this__paths = new java.util.ArrayList<java.lang.String>(other.paths);
      this.paths = __this__paths;
    }
    this.fetchSize = other.fetchSize;
    this.startTime = other.startTime;
    this.endTime = other.endTime;
    this.statementId = other.statementId;
    this.enableRedirectQuery = other.enableRedirectQuery;
    this.jdbcQuery = other.jdbcQuery;
    this.timeout = other.timeout;
    this.legalPathNodes = other.legalPathNodes;
  }

  @Override
  public TSRawDataQueryReq deepCopy() {
    return new TSRawDataQueryReq(this);
  }

  @Override
  public void clear() {
    setSessionIdIsSet(false);
    this.sessionId = 0;
    this.paths = null;
    setFetchSizeIsSet(false);
    this.fetchSize = 0;
    setStartTimeIsSet(false);
    this.startTime = 0;
    setEndTimeIsSet(false);
    this.endTime = 0;
    setStatementIdIsSet(false);
    this.statementId = 0;
    setEnableRedirectQueryIsSet(false);
    this.enableRedirectQuery = false;
    setJdbcQueryIsSet(false);
    this.jdbcQuery = false;
    setTimeoutIsSet(false);
    this.timeout = 0;
    setLegalPathNodesIsSet(false);
    this.legalPathNodes = false;
  }

  public long getSessionId() {
    return this.sessionId;
  }

  public TSRawDataQueryReq setSessionId(long sessionId) {
    this.sessionId = sessionId;
    setSessionIdIsSet(true);
    return this;
  }

  public void unsetSessionId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SESSIONID_ISSET_ID);
  }

  /** Returns true if field sessionId is set (has been assigned a value) and false otherwise */
  public boolean isSetSessionId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SESSIONID_ISSET_ID);
  }

  public void setSessionIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SESSIONID_ISSET_ID, value);
  }

  public int getPathsSize() {
    return (this.paths == null) ? 0 : this.paths.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getPathsIterator() {
    return (this.paths == null) ? null : this.paths.iterator();
  }

  public void addToPaths(java.lang.String elem) {
    if (this.paths == null) {
      this.paths = new java.util.ArrayList<java.lang.String>();
    }
    this.paths.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getPaths() {
    return this.paths;
  }

  public TSRawDataQueryReq setPaths(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> paths) {
    this.paths = paths;
    return this;
  }

  public void unsetPaths() {
    this.paths = null;
  }

  /** Returns true if field paths is set (has been assigned a value) and false otherwise */
  public boolean isSetPaths() {
    return this.paths != null;
  }

  public void setPathsIsSet(boolean value) {
    if (!value) {
      this.paths = null;
    }
  }

  public int getFetchSize() {
    return this.fetchSize;
  }

  public TSRawDataQueryReq setFetchSize(int fetchSize) {
    this.fetchSize = fetchSize;
    setFetchSizeIsSet(true);
    return this;
  }

  public void unsetFetchSize() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FETCHSIZE_ISSET_ID);
  }

  /** Returns true if field fetchSize is set (has been assigned a value) and false otherwise */
  public boolean isSetFetchSize() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FETCHSIZE_ISSET_ID);
  }

  public void setFetchSizeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FETCHSIZE_ISSET_ID, value);
  }

  public long getStartTime() {
    return this.startTime;
  }

  public TSRawDataQueryReq setStartTime(long startTime) {
    this.startTime = startTime;
    setStartTimeIsSet(true);
    return this;
  }

  public void unsetStartTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STARTTIME_ISSET_ID);
  }

  /** Returns true if field startTime is set (has been assigned a value) and false otherwise */
  public boolean isSetStartTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STARTTIME_ISSET_ID);
  }

  public void setStartTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STARTTIME_ISSET_ID, value);
  }

  public long getEndTime() {
    return this.endTime;
  }

  public TSRawDataQueryReq setEndTime(long endTime) {
    this.endTime = endTime;
    setEndTimeIsSet(true);
    return this;
  }

  public void unsetEndTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENDTIME_ISSET_ID);
  }

  /** Returns true if field endTime is set (has been assigned a value) and false otherwise */
  public boolean isSetEndTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENDTIME_ISSET_ID);
  }

  public void setEndTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENDTIME_ISSET_ID, value);
  }

  public long getStatementId() {
    return this.statementId;
  }

  public TSRawDataQueryReq setStatementId(long statementId) {
    this.statementId = statementId;
    setStatementIdIsSet(true);
    return this;
  }

  public void unsetStatementId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STATEMENTID_ISSET_ID);
  }

  /** Returns true if field statementId is set (has been assigned a value) and false otherwise */
  public boolean isSetStatementId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STATEMENTID_ISSET_ID);
  }

  public void setStatementIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STATEMENTID_ISSET_ID, value);
  }

  public boolean isEnableRedirectQuery() {
    return this.enableRedirectQuery;
  }

  public TSRawDataQueryReq setEnableRedirectQuery(boolean enableRedirectQuery) {
    this.enableRedirectQuery = enableRedirectQuery;
    setEnableRedirectQueryIsSet(true);
    return this;
  }

  public void unsetEnableRedirectQuery() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENABLEREDIRECTQUERY_ISSET_ID);
  }

  /** Returns true if field enableRedirectQuery is set (has been assigned a value) and false otherwise */
  public boolean isSetEnableRedirectQuery() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENABLEREDIRECTQUERY_ISSET_ID);
  }

  public void setEnableRedirectQueryIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENABLEREDIRECTQUERY_ISSET_ID, value);
  }

  public boolean isJdbcQuery() {
    return this.jdbcQuery;
  }

  public TSRawDataQueryReq setJdbcQuery(boolean jdbcQuery) {
    this.jdbcQuery = jdbcQuery;
    setJdbcQueryIsSet(true);
    return this;
  }

  public void unsetJdbcQuery() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __JDBCQUERY_ISSET_ID);
  }

  /** Returns true if field jdbcQuery is set (has been assigned a value) and false otherwise */
  public boolean isSetJdbcQuery() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __JDBCQUERY_ISSET_ID);
  }

  public void setJdbcQueryIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __JDBCQUERY_ISSET_ID, value);
  }

  public long getTimeout() {
    return this.timeout;
  }

  public TSRawDataQueryReq setTimeout(long timeout) {
    this.timeout = timeout;
    setTimeoutIsSet(true);
    return this;
  }

  public void unsetTimeout() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIMEOUT_ISSET_ID);
  }

  /** Returns true if field timeout is set (has been assigned a value) and false otherwise */
  public boolean isSetTimeout() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIMEOUT_ISSET_ID);
  }

  public void setTimeoutIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIMEOUT_ISSET_ID, value);
  }

  public boolean isLegalPathNodes() {
    return this.legalPathNodes;
  }

  public TSRawDataQueryReq setLegalPathNodes(boolean legalPathNodes) {
    this.legalPathNodes = legalPathNodes;
    setLegalPathNodesIsSet(true);
    return this;
  }

  public void unsetLegalPathNodes() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LEGALPATHNODES_ISSET_ID);
  }

  /** Returns true if field legalPathNodes is set (has been assigned a value) and false otherwise */
  public boolean isSetLegalPathNodes() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LEGALPATHNODES_ISSET_ID);
  }

  public void setLegalPathNodesIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LEGALPATHNODES_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case SESSION_ID:
      if (value == null) {
        unsetSessionId();
      } else {
        setSessionId((java.lang.Long)value);
      }
      break;

    case PATHS:
      if (value == null) {
        unsetPaths();
      } else {
        setPaths((java.util.List<java.lang.String>)value);
      }
      break;

    case FETCH_SIZE:
      if (value == null) {
        unsetFetchSize();
      } else {
        setFetchSize((java.lang.Integer)value);
      }
      break;

    case START_TIME:
      if (value == null) {
        unsetStartTime();
      } else {
        setStartTime((java.lang.Long)value);
      }
      break;

    case END_TIME:
      if (value == null) {
        unsetEndTime();
      } else {
        setEndTime((java.lang.Long)value);
      }
      break;

    case STATEMENT_ID:
      if (value == null) {
        unsetStatementId();
      } else {
        setStatementId((java.lang.Long)value);
      }
      break;

    case ENABLE_REDIRECT_QUERY:
      if (value == null) {
        unsetEnableRedirectQuery();
      } else {
        setEnableRedirectQuery((java.lang.Boolean)value);
      }
      break;

    case JDBC_QUERY:
      if (value == null) {
        unsetJdbcQuery();
      } else {
        setJdbcQuery((java.lang.Boolean)value);
      }
      break;

    case TIMEOUT:
      if (value == null) {
        unsetTimeout();
      } else {
        setTimeout((java.lang.Long)value);
      }
      break;

    case LEGAL_PATH_NODES:
      if (value == null) {
        unsetLegalPathNodes();
      } else {
        setLegalPathNodes((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SESSION_ID:
      return getSessionId();

    case PATHS:
      return getPaths();

    case FETCH_SIZE:
      return getFetchSize();

    case START_TIME:
      return getStartTime();

    case END_TIME:
      return getEndTime();

    case STATEMENT_ID:
      return getStatementId();

    case ENABLE_REDIRECT_QUERY:
      return isEnableRedirectQuery();

    case JDBC_QUERY:
      return isJdbcQuery();

    case TIMEOUT:
      return getTimeout();

    case LEGAL_PATH_NODES:
      return isLegalPathNodes();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SESSION_ID:
      return isSetSessionId();
    case PATHS:
      return isSetPaths();
    case FETCH_SIZE:
      return isSetFetchSize();
    case START_TIME:
      return isSetStartTime();
    case END_TIME:
      return isSetEndTime();
    case STATEMENT_ID:
      return isSetStatementId();
    case ENABLE_REDIRECT_QUERY:
      return isSetEnableRedirectQuery();
    case JDBC_QUERY:
      return isSetJdbcQuery();
    case TIMEOUT:
      return isSetTimeout();
    case LEGAL_PATH_NODES:
      return isSetLegalPathNodes();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TSRawDataQueryReq)
      return this.equals((TSRawDataQueryReq)that);
    return false;
  }

  public boolean equals(TSRawDataQueryReq that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_sessionId = true;
    boolean that_present_sessionId = true;
    if (this_present_sessionId || that_present_sessionId) {
      if (!(this_present_sessionId && that_present_sessionId))
        return false;
      if (this.sessionId != that.sessionId)
        return false;
    }

    boolean this_present_paths = true && this.isSetPaths();
    boolean that_present_paths = true && that.isSetPaths();
    if (this_present_paths || that_present_paths) {
      if (!(this_present_paths && that_present_paths))
        return false;
      if (!this.paths.equals(that.paths))
        return false;
    }

    boolean this_present_fetchSize = true && this.isSetFetchSize();
    boolean that_present_fetchSize = true && that.isSetFetchSize();
    if (this_present_fetchSize || that_present_fetchSize) {
      if (!(this_present_fetchSize && that_present_fetchSize))
        return false;
      if (this.fetchSize != that.fetchSize)
        return false;
    }

    boolean this_present_startTime = true;
    boolean that_present_startTime = true;
    if (this_present_startTime || that_present_startTime) {
      if (!(this_present_startTime && that_present_startTime))
        return false;
      if (this.startTime != that.startTime)
        return false;
    }

    boolean this_present_endTime = true;
    boolean that_present_endTime = true;
    if (this_present_endTime || that_present_endTime) {
      if (!(this_present_endTime && that_present_endTime))
        return false;
      if (this.endTime != that.endTime)
        return false;
    }

    boolean this_present_statementId = true;
    boolean that_present_statementId = true;
    if (this_present_statementId || that_present_statementId) {
      if (!(this_present_statementId && that_present_statementId))
        return false;
      if (this.statementId != that.statementId)
        return false;
    }

    boolean this_present_enableRedirectQuery = true && this.isSetEnableRedirectQuery();
    boolean that_present_enableRedirectQuery = true && that.isSetEnableRedirectQuery();
    if (this_present_enableRedirectQuery || that_present_enableRedirectQuery) {
      if (!(this_present_enableRedirectQuery && that_present_enableRedirectQuery))
        return false;
      if (this.enableRedirectQuery != that.enableRedirectQuery)
        return false;
    }

    boolean this_present_jdbcQuery = true && this.isSetJdbcQuery();
    boolean that_present_jdbcQuery = true && that.isSetJdbcQuery();
    if (this_present_jdbcQuery || that_present_jdbcQuery) {
      if (!(this_present_jdbcQuery && that_present_jdbcQuery))
        return false;
      if (this.jdbcQuery != that.jdbcQuery)
        return false;
    }

    boolean this_present_timeout = true && this.isSetTimeout();
    boolean that_present_timeout = true && that.isSetTimeout();
    if (this_present_timeout || that_present_timeout) {
      if (!(this_present_timeout && that_present_timeout))
        return false;
      if (this.timeout != that.timeout)
        return false;
    }

    boolean this_present_legalPathNodes = true && this.isSetLegalPathNodes();
    boolean that_present_legalPathNodes = true && that.isSetLegalPathNodes();
    if (this_present_legalPathNodes || that_present_legalPathNodes) {
      if (!(this_present_legalPathNodes && that_present_legalPathNodes))
        return false;
      if (this.legalPathNodes != that.legalPathNodes)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(sessionId);

    hashCode = hashCode * 8191 + ((isSetPaths()) ? 131071 : 524287);
    if (isSetPaths())
      hashCode = hashCode * 8191 + paths.hashCode();

    hashCode = hashCode * 8191 + ((isSetFetchSize()) ? 131071 : 524287);
    if (isSetFetchSize())
      hashCode = hashCode * 8191 + fetchSize;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(startTime);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(endTime);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(statementId);

    hashCode = hashCode * 8191 + ((isSetEnableRedirectQuery()) ? 131071 : 524287);
    if (isSetEnableRedirectQuery())
      hashCode = hashCode * 8191 + ((enableRedirectQuery) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetJdbcQuery()) ? 131071 : 524287);
    if (isSetJdbcQuery())
      hashCode = hashCode * 8191 + ((jdbcQuery) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetTimeout()) ? 131071 : 524287);
    if (isSetTimeout())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(timeout);

    hashCode = hashCode * 8191 + ((isSetLegalPathNodes()) ? 131071 : 524287);
    if (isSetLegalPathNodes())
      hashCode = hashCode * 8191 + ((legalPathNodes) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(TSRawDataQueryReq other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetSessionId(), other.isSetSessionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSessionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sessionId, other.sessionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPaths(), other.isSetPaths());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPaths()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.paths, other.paths);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFetchSize(), other.isSetFetchSize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFetchSize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fetchSize, other.fetchSize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStartTime(), other.isSetStartTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startTime, other.startTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEndTime(), other.isSetEndTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endTime, other.endTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStatementId(), other.isSetStatementId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatementId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.statementId, other.statementId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEnableRedirectQuery(), other.isSetEnableRedirectQuery());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnableRedirectQuery()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.enableRedirectQuery, other.enableRedirectQuery);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetJdbcQuery(), other.isSetJdbcQuery());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJdbcQuery()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jdbcQuery, other.jdbcQuery);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTimeout(), other.isSetTimeout());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimeout()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timeout, other.timeout);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLegalPathNodes(), other.isSetLegalPathNodes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLegalPathNodes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.legalPathNodes, other.legalPathNodes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TSRawDataQueryReq(");
    boolean first = true;

    sb.append("sessionId:");
    sb.append(this.sessionId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("paths:");
    if (this.paths == null) {
      sb.append("null");
    } else {
      sb.append(this.paths);
    }
    first = false;
    if (isSetFetchSize()) {
      if (!first) sb.append(", ");
      sb.append("fetchSize:");
      sb.append(this.fetchSize);
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("startTime:");
    sb.append(this.startTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("endTime:");
    sb.append(this.endTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("statementId:");
    sb.append(this.statementId);
    first = false;
    if (isSetEnableRedirectQuery()) {
      if (!first) sb.append(", ");
      sb.append("enableRedirectQuery:");
      sb.append(this.enableRedirectQuery);
      first = false;
    }
    if (isSetJdbcQuery()) {
      if (!first) sb.append(", ");
      sb.append("jdbcQuery:");
      sb.append(this.jdbcQuery);
      first = false;
    }
    if (isSetTimeout()) {
      if (!first) sb.append(", ");
      sb.append("timeout:");
      sb.append(this.timeout);
      first = false;
    }
    if (isSetLegalPathNodes()) {
      if (!first) sb.append(", ");
      sb.append("legalPathNodes:");
      sb.append(this.legalPathNodes);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'sessionId' because it's a primitive and you chose the non-beans generator.
    if (paths == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'paths' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'startTime' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'endTime' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'statementId' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TSRawDataQueryReqStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TSRawDataQueryReqStandardScheme getScheme() {
      return new TSRawDataQueryReqStandardScheme();
    }
  }

  private static class TSRawDataQueryReqStandardScheme extends org.apache.thrift.scheme.StandardScheme<TSRawDataQueryReq> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TSRawDataQueryReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SESSION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.sessionId = iprot.readI64();
              struct.setSessionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PATHS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list552 = iprot.readListBegin();
                struct.paths = new java.util.ArrayList<java.lang.String>(_list552.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem553;
                for (int _i554 = 0; _i554 < _list552.size; ++_i554)
                {
                  _elem553 = iprot.readString();
                  struct.paths.add(_elem553);
                }
                iprot.readListEnd();
              }
              struct.setPathsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // FETCH_SIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.fetchSize = iprot.readI32();
              struct.setFetchSizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // START_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startTime = iprot.readI64();
              struct.setStartTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // END_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endTime = iprot.readI64();
              struct.setEndTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // STATEMENT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.statementId = iprot.readI64();
              struct.setStatementIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // ENABLE_REDIRECT_QUERY
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.enableRedirectQuery = iprot.readBool();
              struct.setEnableRedirectQueryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // JDBC_QUERY
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.jdbcQuery = iprot.readBool();
              struct.setJdbcQueryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // TIMEOUT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timeout = iprot.readI64();
              struct.setTimeoutIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // LEGAL_PATH_NODES
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.legalPathNodes = iprot.readBool();
              struct.setLegalPathNodesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetSessionId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'sessionId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetStartTime()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'startTime' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetEndTime()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'endTime' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetStatementId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'statementId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TSRawDataQueryReq struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SESSION_ID_FIELD_DESC);
      oprot.writeI64(struct.sessionId);
      oprot.writeFieldEnd();
      if (struct.paths != null) {
        oprot.writeFieldBegin(PATHS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.paths.size()));
          for (java.lang.String _iter555 : struct.paths)
          {
            oprot.writeString(_iter555);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.isSetFetchSize()) {
        oprot.writeFieldBegin(FETCH_SIZE_FIELD_DESC);
        oprot.writeI32(struct.fetchSize);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(START_TIME_FIELD_DESC);
      oprot.writeI64(struct.startTime);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(END_TIME_FIELD_DESC);
      oprot.writeI64(struct.endTime);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STATEMENT_ID_FIELD_DESC);
      oprot.writeI64(struct.statementId);
      oprot.writeFieldEnd();
      if (struct.isSetEnableRedirectQuery()) {
        oprot.writeFieldBegin(ENABLE_REDIRECT_QUERY_FIELD_DESC);
        oprot.writeBool(struct.enableRedirectQuery);
        oprot.writeFieldEnd();
      }
      if (struct.isSetJdbcQuery()) {
        oprot.writeFieldBegin(JDBC_QUERY_FIELD_DESC);
        oprot.writeBool(struct.jdbcQuery);
        oprot.writeFieldEnd();
      }
      if (struct.isSetTimeout()) {
        oprot.writeFieldBegin(TIMEOUT_FIELD_DESC);
        oprot.writeI64(struct.timeout);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLegalPathNodes()) {
        oprot.writeFieldBegin(LEGAL_PATH_NODES_FIELD_DESC);
        oprot.writeBool(struct.legalPathNodes);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TSRawDataQueryReqTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TSRawDataQueryReqTupleScheme getScheme() {
      return new TSRawDataQueryReqTupleScheme();
    }
  }

  private static class TSRawDataQueryReqTupleScheme extends org.apache.thrift.scheme.TupleScheme<TSRawDataQueryReq> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TSRawDataQueryReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.sessionId);
      {
        oprot.writeI32(struct.paths.size());
        for (java.lang.String _iter556 : struct.paths)
        {
          oprot.writeString(_iter556);
        }
      }
      oprot.writeI64(struct.startTime);
      oprot.writeI64(struct.endTime);
      oprot.writeI64(struct.statementId);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetFetchSize()) {
        optionals.set(0);
      }
      if (struct.isSetEnableRedirectQuery()) {
        optionals.set(1);
      }
      if (struct.isSetJdbcQuery()) {
        optionals.set(2);
      }
      if (struct.isSetTimeout()) {
        optionals.set(3);
      }
      if (struct.isSetLegalPathNodes()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetFetchSize()) {
        oprot.writeI32(struct.fetchSize);
      }
      if (struct.isSetEnableRedirectQuery()) {
        oprot.writeBool(struct.enableRedirectQuery);
      }
      if (struct.isSetJdbcQuery()) {
        oprot.writeBool(struct.jdbcQuery);
      }
      if (struct.isSetTimeout()) {
        oprot.writeI64(struct.timeout);
      }
      if (struct.isSetLegalPathNodes()) {
        oprot.writeBool(struct.legalPathNodes);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TSRawDataQueryReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.sessionId = iprot.readI64();
      struct.setSessionIdIsSet(true);
      {
        org.apache.thrift.protocol.TList _list557 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
        struct.paths = new java.util.ArrayList<java.lang.String>(_list557.size);
        @org.apache.thrift.annotation.Nullable java.lang.String _elem558;
        for (int _i559 = 0; _i559 < _list557.size; ++_i559)
        {
          _elem558 = iprot.readString();
          struct.paths.add(_elem558);
        }
      }
      struct.setPathsIsSet(true);
      struct.startTime = iprot.readI64();
      struct.setStartTimeIsSet(true);
      struct.endTime = iprot.readI64();
      struct.setEndTimeIsSet(true);
      struct.statementId = iprot.readI64();
      struct.setStatementIdIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.fetchSize = iprot.readI32();
        struct.setFetchSizeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.enableRedirectQuery = iprot.readBool();
        struct.setEnableRedirectQueryIsSet(true);
      }
      if (incoming.get(2)) {
        struct.jdbcQuery = iprot.readBool();
        struct.setJdbcQueryIsSet(true);
      }
      if (incoming.get(3)) {
        struct.timeout = iprot.readI64();
        struct.setTimeoutIsSet(true);
      }
      if (incoming.get(4)) {
        struct.legalPathNodes = iprot.readBool();
        struct.setLegalPathNodesIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

