/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.iotdb.db.queryengine.plan.relational.planner.node;

import org.apache.iotdb.db.queryengine.plan.planner.plan.node.PlanNode;
import org.apache.iotdb.db.queryengine.plan.planner.plan.node.PlanNodeId;
import org.apache.iotdb.db.queryengine.plan.planner.plan.node.PlanNodeType;
import org.apache.iotdb.db.queryengine.plan.planner.plan.node.PlanVisitor;
import org.apache.iotdb.db.queryengine.plan.relational.planner.OrderingScheme;

import com.google.common.collect.Iterables;
import org.apache.tsfile.utils.ReadWriteIOUtils;

import java.io.DataOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.List;

/**
 * Auxiliary node for sorting. Not generated by user queries, it is used by special process such as
 * table function.
 */
public class AuxSortNode extends SortNode {

  private boolean enableParalleled = false;

  /**
   * AuxSort#orderingScheme may include two parts: partition key and sort key. For example,
   * PARTITION BY device_id, color ORDER BY time will construct an AuxSortNode with
   * OrderingScheme[device_id, color, time] and partitionColumnCount = 2.
   */
  private int partitionKeyCount;

  public AuxSortNode(PlanNodeId id, PlanNode child, OrderingScheme scheme, int partitionKeyCount) {
    super(id, child, scheme, false, false);
    this.partitionKeyCount = partitionKeyCount;
  }

  public AuxSortNode(
      PlanNodeId id,
      PlanNode child,
      OrderingScheme scheme,
      boolean partial,
      boolean orderByAllIdsAndTime,
      boolean enableParalleled,
      int partitionKeyCount) {
    super(id, child, scheme, partial, orderByAllIdsAndTime);
    this.enableParalleled = enableParalleled;
    this.partitionKeyCount = partitionKeyCount;
  }

  @Override
  public PlanNode replaceChildren(List<PlanNode> newChildren) {
    return new AuxSortNode(
        id,
        Iterables.getOnlyElement(newChildren),
        orderingScheme,
        partial,
        orderByAllIdsAndTime,
        enableParalleled,
        partitionKeyCount);
  }

  public boolean isEnableParalleled() {
    return enableParalleled;
  }

  public void setEnableParalleled(boolean enableParalleled) {
    this.enableParalleled = enableParalleled;
  }

  public int getPartitionKeyCount() {
    return partitionKeyCount;
  }

  @Override
  public <R, C> R accept(PlanVisitor<R, C> visitor, C context) {
    return visitor.visitAuxSort(this, context);
  }

  @Override
  public PlanNode clone() {
    return new AuxSortNode(
        id,
        null,
        orderingScheme,
        partial,
        orderByAllIdsAndTime,
        enableParalleled,
        partitionKeyCount);
  }

  @Override
  protected void serializeAttributes(ByteBuffer byteBuffer) {
    PlanNodeType.TABLE_AUX_SORT_NODE.serialize(byteBuffer);
    orderingScheme.serialize(byteBuffer);
    ReadWriteIOUtils.write(enableParalleled, byteBuffer);
    ReadWriteIOUtils.write(partitionKeyCount, byteBuffer);
  }

  @Override
  protected void serializeAttributes(DataOutputStream stream) throws IOException {
    PlanNodeType.TABLE_AUX_SORT_NODE.serialize(stream);
    orderingScheme.serialize(stream);
    ReadWriteIOUtils.write(enableParalleled, stream);
    ReadWriteIOUtils.write(partitionKeyCount, stream);
  }

  public static AuxSortNode deserialize(ByteBuffer byteBuffer) {
    OrderingScheme orderingScheme = OrderingScheme.deserialize(byteBuffer);
    boolean enableParalleled = ReadWriteIOUtils.readBoolean(byteBuffer);
    int partitionColumnCount = ReadWriteIOUtils.readInt(byteBuffer);
    PlanNodeId planNodeId = PlanNodeId.deserialize(byteBuffer);
    return new AuxSortNode(
        planNodeId, null, orderingScheme, false, false, enableParalleled, partitionColumnCount);
  }

  @Override
  public String toString() {
    return "AuxSortNode-" + this.getPlanNodeId();
  }
}
