/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.  See the NOTICE file distributed with this work for additional information regarding copyright ownership.  The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.  You may obtain a copy of the License at      http://www.apache.org/licenses/LICENSE-2.0  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the License for the specific language governing permissions and limitations under the License.
 */

package org.apache.iotdb.cluster.partition;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * When a new node is added, the local node may encounter one of the three changes:
 * 1. the node joins a new group generated by the new node.
 * 2. the new node is added to the node's subordinate group, but the local
 *    node is not the last node and thus still remains.
 * 3. the new node is added to the node's subordinate group, and the local
 *    node is the last node and thus leaves the group.
 * Those three kinds of groups are named newGroups, changedGroups and retireGroups respectively.
 */
public class AddNodePartitionUpdate {

  PartitionGroup newGroup;
  List<PartitionGroup> changedGroups = new ArrayList<>();
  List<PartitionGroup> retiredGroups = new ArrayList<>();
}
