/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.iotdb.cluster.partition;

import java.nio.ByteBuffer;
import java.util.List;
import java.util.Map;
import org.apache.commons.collections4.map.MultiKeyMap;
import org.apache.iotdb.cluster.rpc.thrift.Node;
import org.apache.iotdb.db.engine.StorageEngine;
import org.apache.iotdb.db.exception.metadata.MetadataException;
import org.apache.iotdb.db.exception.metadata.StorageGroupNotSetException;
import org.apache.iotdb.db.metadata.MManager;

/**
 * PartitionTable manages the map whose key is the StorageGroupName with a time interval and the
 * value is a PartitionGroup with contains all nodes that manage the corresponding data.
 * currently, we do not support auto-create storage group in the cluster mode.
 */
public interface PartitionTable {

  /**
   * Given the storageGroupName and the timestamp, return the list of nodes on which the storage
   * group and the corresponding time interval is managed.
   *
   * @param storageGroupName
   * @param timestamp
   * @return
   */
  PartitionGroup route(String storageGroupName, long timestamp);

  PartitionGroup route(int hashKey);

  /**
   * Given the storageGroupName and the timestamp, return the header node of the partitionGroup by
   * which the storage group and the corresponding time interval is managed.
   *
   * @param storageGroupName
   * @param timestamp
   * @return
   */
  Node routeToHeaderByTime(String storageGroupName, long timestamp);

  /**
   * get a unicode value for a sg and a timestamp.
   *
   * @param storageGroupName
   * @param timestamp
   * @return
   */
  int getPartitionKey(String storageGroupName, long timestamp);


  /**
   * Add a new node to update the partition table.
   *
   * @param node
   * @return the new group generated by the node
   */
  PartitionGroup addNode(Node node);

  /**
   * Remove a node and update the partition table.
   *
   * @param node
   */
  NodeRemovalResult removeNode(Node node);

  /**
   * @return All data groups where all VNodes of this node is the header. The first index indicates
   * the VNode and the second index indicates the data group of one VNode.
   */
  List<PartitionGroup> getLocalGroups();

  /**
   * @param header
   * @return the partition group starting from the header.
   */
  PartitionGroup getHeaderGroup(Node header);

  ByteBuffer serialize();

  void deserialize(ByteBuffer buffer);

  List<Node> getAllNodes();

  /**
   * @return each slot's previous holder after the node's addition.
   */
  Map<Integer, Node> getPreviousNodeMap(Node node);

  /**
   * @param header
   * @return the slots held by the header.
   */
  List<Integer> getNodeSlots(Node header);

  Map<Node, List<Integer>> getAllNodeSlots();

  int getTotalSlotNumbers();

  MManager getMManager();

  List<PartitionGroup> getGlobalGroups();

  /**
   * @param path      can be an incomplete path (but should contain a storage group name) e.g., if
   *                  "root.sg" is a storage group, then path can not be "root".
   * @param timestamp
   * @return
   * @throws StorageGroupNotSetException
   */
  default PartitionGroup partitionByPathTime(String path, long timestamp)
      throws MetadataException {
    String storageGroup = getMManager().getStorageGroupName(path);
    return this.route(storageGroup, timestamp);
  }

  /**
   * Get partition info by path and range time
   *
   * @return (startTime, endTime) - partitionGroup pair
   * @UsedBy NodeTool
   */
  default MultiKeyMap<Long, PartitionGroup> partitionByPathRangeTime(String path,
      long startTime, long endTime) throws MetadataException {
    long partitionInterval = StorageEngine.getTimePartitionInterval();

    MultiKeyMap<Long, PartitionGroup> timeRangeMapRaftGroup = new MultiKeyMap<>();
    String storageGroup = getMManager().getStorageGroupName(path);
    startTime = StorageEngine.convertMilliWithPrecision(startTime);
    endTime = StorageEngine.convertMilliWithPrecision(endTime);
    while (startTime <= endTime) {
      long nextTime = (startTime / partitionInterval + 1)
          * partitionInterval;
      timeRangeMapRaftGroup.put(startTime, Math.min(nextTime - 1, endTime),
          this.route(storageGroup, startTime));
      startTime = nextTime;
    }
    return timeRangeMapRaftGroup;
  }


}
