name: Daily IT

on:
  schedule:
    # Run at UTC 19:00 every day (CST 03:00 AM)
    - cron: '0 19 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
  MAVEN_ARGS: --batch-mode --no-transfer-progress
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  Simple:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        java: [ 8, 17 ]
    runs-on: [self-hosted, iotdb]
    #      group: self-hosted
    #      labels: iotdb
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: IT/UT Test
        shell: bash
        run: |
          mvn clean verify \
          -P with-integration-tests \
          -DskipUTs \
          -DintegrationTest.forkCount=6 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 \
          -pl integration-test \
          -am -PDailyIT
      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cluster-log-java${{ matrix.java }}-${{ runner.os }}
          path: integration-test/target/cluster-logs
          retention-days: 3
  SingleRegionTableModel:
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        java: [ 8, 17 ]
    runs-on: [ self-hosted, iotdb ]
    #      group: self-hosted
    #      labels: iotdb
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: IT/UT Test
        shell: bash
        # we do not compile client-cpp for saving time, it is tested in client.yml
        # we can skip influxdb-protocol because it has been tested separately in influxdb-protocol.yml
        run: |
          mvn clean verify \
          -P with-integration-tests \
          -DskipUTs \
          -DintegrationTest.forkCount=2 -DDataNodeMaxHeapSize=1024 -DintegrationTest.dataRegionPerDataNode=1\
          -pl integration-test \
          -am -PTableSimpleIT
      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: table-standalone-log-java${{ matrix.java }}-${{ runner.os }}
          path: integration-test/target/cluster-logs
          retention-days: 3