name: Grafana plugin build

on:
  push:
    branches:
      - master
      - 'rel/1.*'
    paths-ignore:
      - 'docs/**'
      - 'site/**'
  pull_request:
    branches:
      - master
      - "new_*"
    paths-ignore:
      - 'docs/**'
      - 'site/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'iotdb-connector/grafana-plugin'
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "1.20"


      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn cache
        uses: actions/cache@v3
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: list dir
        run: |
          ls
          yarn install --frozen-lockfile
          yarn build

      - name: Install dependencies and Build and test frontend
        run: |
          cd iotdb-connector/grafana-plugin/
          yarn install --frozen-lockfile
          yarn build

#      - name: Install dependencies and Build backend
#        run: |
#          cd iotdb-connector/grafana-plugin/
#          ./backend-compile.sh

      - name: Build backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: buildAll
