name: Grafana plugin build

on:
  push:
    branches:
      - master
      - "new_*"
    paths:
      - 'iotdb-connector/grafana-plugin/**'
  pull_request:
    branches:
      - master
      - "new_*"
    paths:
      - 'iotdb-connector/grafana-plugin/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "14.x"

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn cache
        uses: actions/cache@v4
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Install dependencies and Build and test frontend
        run: |
          cd iotdb-connector/grafana-plugin/
          yarn install --frozen-lockfile
          yarn build

      - name: Install dependencies and Build backend
        run: |
          cd iotdb-connector/grafana-plugin/
          ./backend-compile.sh
