name: AINode Code Style Check

on:
  push:
    branches:
      - master
      - 'rel/*'
      - 'rc/*'
    paths-ignore:
      - 'docs/**'
      - 'site/**'
  pull_request:
    branches:
      - master
      - 'rel/*'
      - 'rc/*'
      - 'force_ci/**'
    paths-ignore:
      - 'docs/**'
      - 'site/**'
  # allow manually run the action:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
  MAVEN_ARGS: --batch-mode --no-transfer-progress
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  check-style:
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Build AINode
        shell: bash
        run: mvn clean package -DskipTests -P with-ainode

      - name: Activate python venv
        shell: bash
        run: |
          cd iotdb-core/ainode && source venv/bin/activate && poetry install

      - name: Check code formatting (Black)
        run: |
          cd iotdb-core/ainode && black --check .
        continue-on-error: false

      - name: Check import order (Isort)
        run: |
          cd iotdb-core/ainode && isort --check-only --profile black .
        continue-on-error: false