name: AINode Code Style Check

on:
  push:
    branches:
      - master
      - 'rel/*'
      - 'rc/*'
    paths-ignore:
      - 'docs/**'
      - 'site/**'
  pull_request:
    branches:
      - master
      - 'rel/*'
      - 'rc/*'
    paths-ignore:
      - 'docs/**'
      - 'site/**'
  # allow manually run the action:
  workflow_dispatch:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd iotdb-core/ainode
          poetry install

      - name: Check code formatting (Black)
        run: |
          cd iotdb-core/ainode
          black --check .
        continue-on-error: false

      - name: Check import order (Isort)
        run: |
          cd iotdb-core/ainode
          isort --check-only --profile black .
        continue-on-error: false